#### Handling Imbalanced Data

(a.)  Upsampling ------>

It refers to the technique of increasing the minority class samples so as to make it at par with the majority class samples.

In [154]:
#### Load the Dataset

import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns


from    sklearn.utils       import  resample

In [155]:
### Load the dataset

df = pd.read_csv("diabetes.csv")

In [156]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [157]:
#### Count the categories of Outcome '0' and Outcome '1' 

df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

#### OBSERVATIONS:

1.  Here we see that the count of the category 0 is much higher than the count of category 1. So here we need to perform upsampling so as to increase the count of the category 1. 

2.  Thus the count of category 1 will be at par with the count of category 0

In [158]:
#### perform upsampling

df_majority = df[df['Outcome'] == 0]

df_minority = df[df['Outcome'] == 1]

In [159]:
df_majority

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,1,85,66,29,0,26.6,0.351,31,0
3,1,89,66,23,94,28.1,0.167,21,0
5,5,116,74,0,0,25.6,0.201,30,0
7,10,115,0,0,0,35.3,0.134,29,0
10,4,110,92,0,0,37.6,0.191,30,0
...,...,...,...,...,...,...,...,...,...
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
767,1,93,70,31,0,30.4,0.315,23,0

In [160]:
df_minority

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
...,...,...,...,...,...,...,...,...,...
755,1,128,88,39,110,36.5,1.057,37,1
757,0,123,72,0,0,36.3,0.258,52,1
759,6,190,92,0,0,35.5,0.278,66,1
761,9,170,74,31,0,44.0,0.403,43,1
766,1,126,60,0,0,30.1,0.349,47,1

In [161]:
#### perform the upsampling on the minority class

df_minority_upsample = resample(
                                 df_minority                                      ,
                                 replace        =     True                        ,
                                 n_samples      =     len(df_majority)            ,
                                 random_state   =       42  
                                )

In [162]:
df_minority_upsample

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
269,2,146,0,0,0,27.5,0.240,28,1
283,7,161,86,0,0,30.4,0.165,47,1
195,5,158,84,41,210,39.4,0.395,29,1
535,4,132,0,0,0,32.9,0.302,23,1
38,2,90,68,42,0,38.2,0.503,27,1
...,...,...,...,...,...,...,...,...,...
612,7,168,88,42,321,38.2,0.787,40,1
586,8,143,66,0,0,34.9,0.129,41,1
730,3,130,78,23,79,28.4,0.323,34,1
664,6,115,60,39,0,33.7,0.245,40,1
425,4,184,78,39,277,37.0,0.264,31,1

In [163]:
#### Join the resampled data

df_new = pd.concat([df_majority, df_minority_upsample])

In [164]:
df_new['Outcome'].value_counts()

Outcome
0    500
1    500
Name: count, dtype: int64

#### OBSERVATIONS:

1.  After performing the upsampling technique, the count of the minority class has been increased and has been at par with the majority class.

(b.)  Downsampling -------->

It refers to the technique of decreasing the majority data points so as to make it at par with the minority data points.

In [165]:
from  sklearn.utils  import  resample



##### perform the Downsampling on the majority data points

### Load the dataset

df = pd.read_csv("diabetes.csv")

print(df)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age  Outcome
0                       0.627   50        1
1                       0.351   31        0
2                       0.672   32        1
3                       0.167   21        0
4                       2.288   33        1
..                        ...  ...      ...
763                     0.171   63        0
764                     0.340   27        0
765                     0.245   30        0
766                     0.349   47        1
767                     0.315   23        0

[768 rows x 9 columns]

In [166]:
#### Count the values in each categories

df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [167]:
#### perform the downsampling on the majority data points

df_majority_downsample = resample(
    df_majority                                                ,
    replace           =             True                       ,
    n_samples         =             len(df_minority)           ,  
    random_state      =               42
)

In [168]:
#### Join  the  resamples data

df_new = pd.concat([df_minority, df_majority_downsample])

In [169]:
df_new

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1
...,...,...,...,...,...,...,...,...,...
499,6,154,74,32,193,29.3,0.839,39,0
763,10,101,76,48,180,32.9,0.171,63,0
672,10,68,106,23,49,35.5,0.285,47,0
85,2,110,74,29,125,32.4,0.698,27,0
433,2,139,75,0,0,25.6,0.167,29,0

In [170]:
#### Again count the values in each categories for the resmaples data

df_new['Outcome'].value_counts()

Outcome
1    268
0    268
Name: count, dtype: int64

#### OBSERVATIONS:

1.  After performing the downsampling technique, the count of the majority class has been decreased and has been at par with the minority class.