## **Word2Vec**

1.  Word2Vec is a word embedding technique that is used to convert each and every input word into the dense dimensional numerical vector so that it can easily be trained by the machine learning model while preserving its semantic meaning.

2.  Words with the similar meaning will have the same numerical vector valued representations.

## **Problem Stetement:**

1.  The main aim of the problem statement is to find out the vector representation of each and every word and find out the similar words w.r.to the particular word and even compute the similarity ratio between the two words.


## **Step 1: Import all the necessary libraries**

In [194]:
!pip install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.1)

In [195]:
import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns

import  nltk

from    nltk.tokenize       import  word_tokenize
from    gensim.models       import  Word2Vec

#### OBSERVATIONS:

1.  gensim --------------->   A model used for embedding

2.  word_tokenize -------->  converts the sentences into the words

## **Step 2: Download the necessary resources required for NLTK**

In [196]:
#### Download the necessary resources
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

## **OBSERVATIONS:**

1.  punkt_tab ---------->  It is a pre trained tokenizer required for tokenization process.

2.  averaged_perceptron_tagger_eng --------> It is needed for POS Tagging.

3.  stopwords -----------> It is needed for the removal of the stop words

## **Step 3: Load the Dataset**

In [197]:
### Load the dataset

df = pd.read_csv('/content/SMSSpamCollection',sep='\t',names=['label','message'])

In [198]:
df

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [199]:
#### Interchange the positions of the message and the labels

df=df[['message','label']]

In [200]:
df

                                                message label
0     Go until jurong point, crazy.. Available only ...   ham
1                         Ok lar... Joking wif u oni...   ham
2     Free entry in 2 a wkly comp to win FA Cup fina...  spam
3     U dun say so early hor... U c already then say...   ham
4     Nah I don't think he goes to usf, he lives aro...   ham
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...  spam
5568               Will ü b going to esplanade fr home?   ham
5569  Pity, * was in mood for that. So...any other s...   ham
5570  The guy did some bitching but I acted like i'd...   ham
5571                         Rofl. Its true to its name   ham

[5572 rows x 2 columns]

## **OBSERVATIONS:**

1.  The dataset has been created with two columns as follows:---

    (a.)  message -------->  It specifies the type of the email message.

    (b.)  label   -------->  It specifies the type of the message whether it is 'ham' or 'spam'.

## **Step 4: Perform Text Preprocessing**

In [201]:
### perform word tokenization on all the sentences in the message column

res = [word_tokenize(x.lower()) for x in df['message']]

In [202]:
res

[['go',
  'until',
  'jurong',
  'point',
  ',',
  'crazy',
  '..',
  'available',
  'only',
  'in',
  'bugis',
  'n',
  'great',
  'world',
  'la',
  'e',
  'buffet',
  '...',
  'cine',
  'there',
  'got',
  'amore',
  'wat',
  '...'],
 ['ok', 'lar', '...', 'joking', 'wif', 'u', 'oni', '...'],
 ['free',
  'entry',
  'in',
  '2',
  'a',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  '21st',
  'may',
  '2005.',
  'text',
  'fa',
  'to',
  '87121',
  'to',
  'receive',
  'entry',
  'question',
  '(',
  'std',
  'txt',
  'rate',
  ')',
  't',
  '&',
  'c',
  "'s",
  'apply',
  '08452810075over18',
  "'s"],
 ['u',
  'dun',
  'say',
  'so',
  'early',
  'hor',
  '...',
  'u',
  'c',
  'already',
  'then',
  'say',
  '...'],
 ['nah',
  'i',
  'do',
  "n't",
  'think',
  'he',
  'goes',
  'to',
  'usf',
  ',',
  'he',
  'lives',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  "'s",
  'been',
  '3',
  'week',
  "'s",
  'now',
  'and',
  'no',
  'word',
  'back',
  '!',
  'i',
  "'d",
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  '?',
  'tb',
  'ok',
  '!',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  ',',
  '£1.50',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'speak',
  'with',
  'me',
  '.',
  'they',
  'treat',
  'me',
  'like',
  'aids',
  'patent',
  '.'],
 ['as',
  'per',
  'your',
  'request',
  "'melle",
  'melle',
  '(',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  ')',
  "'",
  'has',
  'been',
  'set',
  'as',
  'your',
  'callertune',
  'for',
  'all',
  'callers',
  '.',
  'press',
  '*',
  '9',
  'to',
  'copy',
  'your',
  'friends',
  'callertune'],
 ['winner',
  '!',
  '!',
  'as',
  'a',
  'valued',
  'network',
  'customer',
  'you',
  'have',
  'been',
  'selected',
  'to',
  'receivea',
  '£900',
  'prize',
  'reward',
  '!',
  'to',
  'claim',
  'call',
  '09061701461.',
  'claim',
  'code',
  'kl341',
  '.',
  'valid',
  '12',
  'hours',
  'only',
  '.'],
 ['had',
  'your',
  'mobile',
  '11',
  'months',
  'or',
  'more',
  '?',
  'u',
  'r',
  'entitled',
  'to',
  'update',
  'to',
  'the',
  'latest',
  'colour',
  'mobiles',
  'with',
  'camera',
  'for',
  'free',
  '!',
  'call',
  'the',
  'mobile',
  'update',
  'co',
  'free',
  'on',
  '08002986030'],
 ['i',
  "'m",
  'gon',
  'na',
  'be',
  'home',
  'soon',
  'and',
  'i',
  'do',
  "n't",
  'want',
  'to',
  'talk',
  'about',
  'this',
  'stuff',
  'anymore',
  'tonight',
  ',',
  'k',
  '?',
  'i',
  "'ve",
  'cried',
  'enough',
  'today',
  '.'],
 ['six',
  'chances',
  'to',
  'win',
  'cash',
  '!',
  'from',
  '100',
  'to',
  '20,000',
  'pounds',
  'txt',
  '>',
  'csh11',
  'and',
  'send',
  'to',
  '87575.',
  'cost',
  '150p/day',
  ',',
  '6days',
  ',',
  '16+',
  'tsandcs',
  'apply',
  'reply',
  'hl',
  '4',
  'info'],
 ['urgent',
  '!',
  'you',
  'have',
  'won',
  'a',
  '1',
  'week',
  'free',
  'membership',
  'in',
  'our',
  '£100,000',
  'prize',
  'jackpot',
  '!',
  'txt',
  'the',
  'word',
  ':',
  'claim',
  'to',
  'no',
  ':',
  '81010',
  't',
  '&',
  'c',
  'www.dbuk.net',
  'lccltd',
  'pobox',
  '4403ldnw1a7rw18'],
 ['i',
  "'ve",
  'been',
  'searching',
  'for',
  'the',
  'right',
  'words',
  'to',
  'thank',
  'you',
  'for',
  'this',
  'breather',
  '.',
  'i',
  'promise',
  'i',
  'wont',
  'take',
  'your',
  'help',
  'for',
  'granted',
  'and',
  'will',
  'fulfil',
  'my',
  'promise',
  '.',
  'you',
  'have',
  'been',
  'wonderful',
  'and',
  'a',
  'blessing',
  'at',
  'all',
  'times',
  '.'],
 ['i', 'have', 'a', 'date', 'on', 'sunday', 'with', 'will', '!', '!'],
 ['xxxmobilemovieclub',
  ':',
  'to',
  'use',
  'your',
  'credit',
  ',',
  'click',
  'the',
  'wap',
  'link',
  'in',
  'the',
  'next',
  'txt',
  'message',
  'or',
  'click',
  'here',
  '>',
  '>',
  'http',
  ':',
  '//wap',
  '.',
  'xxxmobilemovieclub.com',
  '?',
  'n=qjkgighjjgcbl'],
 ['oh', 'k', '...', 'i', "'m", 'watching', 'here', ':', ')'],
 ['eh',
  'u',
  'remember',
  'how',
  '2',
  'spell',
  'his',
  'name',
  '...',
  'yes',
  'i',
  'did',
  '.',
  'he',
  'v',
  'naughty',
  'make',
  'until',
  'i',
  'v',
  'wet',
  '.'],
 ['fine',
  'if',
  'that\x92s',
  'the',
  'way',
  'u',
  'feel',
  '.',
  'that\x92s',
  'the',
  'way',
  'its',
  'gota',
  'b'],
 ['england',
  'v',
  'macedonia',
  '-',
  'dont',
  'miss',
  'the',
  'goals/team',
  'news',
  '.',
  'txt',
  'ur',
  'national',
  'team',
  'to',
  '87077',
  'eg',
  'england',
  'to',
  '87077',
  'try',
  ':',
  'wales',
  ',',
  'scotland',
  '4txt/ú1.20',
  'poboxox36504w45wq',
  '16+'],
 ['is', 'that', 'seriously', 'how', 'you', 'spell', 'his', 'name', '?'],
 ['i',
  '‘',
  'm',
  'going',
  'to',
  'try',
  'for',
  '2',
  'months',
  'ha',
  'ha',
  'only',
  'joking'],
 ['so',
  'ü',
  'pay',
  'first',
  'lar',
  '...',
  'then',
  'when',
  'is',
  'da',
  'stock',
  'comin',
  '...'],
 ['aft',
  'i',
  'finish',
  'my',
  'lunch',
  'then',
  'i',
  'go',
  'str',
  'down',
  'lor',
  '.',
  'ard',
  '3',
  'smth',
  'lor',
  '.',
  'u',
  'finish',
  'ur',
  'lunch',
  'already',
  '?'],
 ['ffffffffff',
  '.',
  'alright',
  'no',
  'way',
  'i',
  'can',
  'meet',
  'up',
  'with',
  'you',
  'sooner',
  '?'],
 ['just',
  'forced',
  'myself',
  'to',
  'eat',
  'a',
  'slice',
  '.',
  'i',
  "'m",
  'really',
  'not',
  'hungry',
  'tho',
  '.',
  'this',
  'sucks',
  '.',
  'mark',
  'is',
  'getting',
  'worried',
  '.',
  'he',
  'knows',
  'i',
  "'m",
  'sick',
  'when',
  'i',
  'turn',
  'down',
  'pizza',
  '.',
  'lol'],
 ['lol', 'your', 'always', 'so', 'convincing', '.'],
 ['did',
  'you',
  'catch',
  'the',
  'bus',
  '?',
  'are',
  'you',
  'frying',
  'an',
  'egg',
  '?',
  'did',
  'you',
  'make',
  'a',
  'tea',
  '?',
  'are',
  'you',
  'eating',
  'your',
  'mom',
  "'s",
  'left',
  'over',
  'dinner',
  '?',
  'do',
  'you',
  'feel',
  'my',
  'love',
  '?'],
 ['i',
  "'m",
  'back',
  '&',
  'amp',
  ';',
  'we',
  "'re",
  'packing',
  'the',
  'car',
  'now',
  ',',
  'i',
  "'ll",
  'let',
  'you',
  'know',
  'if',
  'there',
  "'s",
  'room'],
 ['ahhh',
  '.',
  'work',
  '.',
  'i',
  'vaguely',
  'remember',
  'that',
  '!',
  'what',
  'does',
  'it',
  'feel',
  'like',
  '?',
  'lol'],
 ['wait',
  'that',
  "'s",
  'still',
  'not',
  'all',
  'that',
  'clear',
  ',',
  'were',
  'you',
  'not',
  'sure',
  'about',
  'me',
  'being',
  'sarcastic',
  'or',
  'that',
  'that',
  "'s",
  'why',
  'x',
  'does',
  "n't",
  'want',
  'to',
  'live',
  'with',
  'us'],
 ['yeah',
  'he',
  'got',
  'in',
  'at',
  '2',
  'and',
  'was',
  'v',
  'apologetic',
  '.',
  'n',
  'had',
  'fallen',
  'out',
  'and',
  'she',
  'was',
  'actin',
  'like',
  'spoilt',
  'child',
  'and',
  'he',
  'got',
  'caught',
  'up',
  'in',
  'that',
  '.',
  'till',
  '2',
  '!',
  'but',
  'we',
  'wo',
  "n't",
  'go',
  'there',
  '!',
  'not',
  'doing',
  'too',
  'badly',
  'cheers',
  '.',
  'you',
  '?'],
 ['k', 'tell', 'me', 'anything', 'about', 'you', '.'],
 ['for',
  'fear',
  'of',
  'fainting',
  'with',
  'the',
  'of',
  'all',
  'that',
  'housework',
  'you',
  'just',
  'did',
  '?',
  'quick',
  'have',
  'a',
  'cuppa'],
 ['thanks',
  'for',
  'your',
  'subscription',
  'to',
  'ringtone',
  'uk',
  'your',
  'mobile',
  'will',
  'be',
  'charged',
  '£5/month',
  'please',
  'confirm',
  'by',
  'replying',
  'yes',
  'or',
  'no',
  '.',
  'if',
  'you',
  'reply',
  'no',
  'you',
  'will',
  'not',
  'be',
  'charged'],
 ['yup',
  '...',
  'ok',
  'i',
  'go',
  'home',
  'look',
  'at',
  'the',
  'timings',
  'then',
  'i',
  'msg',
  'ü',
  'again',
  '...',
  'xuhui',
  'going',
  'to',
  'learn',
  'on',
  '2nd',
  'may',
  'too',
  'but',
  'her',
  'lesson',
  'is',
  'at',
  '8am'],
 ['oops',
  ',',
  'i',
  "'ll",
  'let',
  'you',
  'know',
  'when',
  'my',
  'roommate',
  "'s",
  'done'],
 ['i', 'see', 'the', 'letter', 'b', 'on', 'my', 'car'],
 ['anything', 'lor', '...', 'u', 'decide', '...'],
 ['hello',
  '!',
  'how',
  "'s",
  'you',
  'and',
  'how',
  'did',
  'saturday',
  'go',
  '?',
  'i',
  'was',
  'just',
  'texting',
  'to',
  'see',
  'if',
  'you',
  "'d",
  'decided',
  'to',
  'do',
  'anything',
  'tomo',
  '.',
  'not',
  'that',
  'i',
  "'m",
  'trying',
  'to',
  'invite',
  'myself',
  'or',
  'anything',
  '!'],
 ['pls',
  'go',
  'ahead',
  'with',
  'watts',
  '.',
  'i',
  'just',
  'wanted',
  'to',
  'be',
  'sure',
  '.',
  'do',
  'have',
  'a',
  'great',
  'weekend',
  '.',
  'abiola'],
 ['did',
  'i',
  'forget',
  'to',
  'tell',
  'you',
  '?',
  'i',
  'want',
  'you',
  ',',
  'i',
  'need',
  'you',
  ',',
  'i',
  'crave',
  'you',
  '...',
  'but',
  'most',
  'of',
  'all',
  '...',
  'i',
  'love',
  'you',
  'my',
  'sweet',
  'arabian',
  'steed',
  '...',
  'mmmmmm',
  '...',
  'yummy'],
 ['07732584351',
  '-',
  'rodger',
  'burns',
  '-',
  'msg',
  '=',
  'we',
  'tried',
  'to',
  'call',
  'you',
  're',
  'your',
  'reply',
  'to',
  'our',
  'sms',
  'for',
  'a',
  'free',
  'nokia',
  'mobile',
  '+',
  'free',
  'camcorder',
  '.',
  'please',
  'call',
  'now',
  '08000930705',
  'for',
  'delivery',
  'tomorrow'],
 ['who', 'are', 'you', 'seeing', '?'],
 ['great',
  '!',
  'i',
  'hope',
  'you',
  'like',
  'your',
  'man',
  'well',
  'endowed',
  '.',
  'i',
  'am',
  '&',
  'lt',
  ';',
  '#',
  '&',
  'gt',
  ';',
  'inches',
  '...'],
 ['no', 'calls', '..', 'messages', '..', 'missed', 'calls'],
 ['did',
  "n't",
  'you',
  'get',
  'hep',
  'b',
  'immunisation',
  'in',
  'nigeria',
  '.'],
 ['fair', 'enough', ',', 'anything', 'going', 'on', '?'],
 ['yeah',
  'hopefully',
  ',',
  'if',
  'tyler',
  'ca',
  "n't",
  'do',
  'it',
  'i',
  'could',
  'maybe',
  'ask',
  'around',
  'a',
  'bit'],
 ['u',
  'do',
  "n't",
  'know',
  'how',
  'stubborn',
  'i',
  'am',
  '.',
  'i',
  'did',
  "n't",
  'even',
  'want',
  'to',
  'go',
  'to',
  'the',
  'hospital',
  '.',
  'i',
  'kept',
  'telling',
  'mark',
  'i',
  "'m",
  'not',
  'a',
  'weak',
  'sucker',
  '.',
  'hospitals',
  'are',
  'for',
  'weak',
  'suckers',
  '.'],
 ['what',
  'you',
  'thinked',
  'about',
  'me',
  '.',
  'first',
  'time',
  'you',
  'saw',
  'me',
  'in',
  'class',
  '.'],
 ['a',
  'gram',
  'usually',
  'runs',
  'like',
  '&',
  'lt',
  ';',
  '#',
  '&',
  'gt',
  ';',
  ',',
  'a',
  'half',
  'eighth',
  'is',
  'smarter',
  'though',
  'and',
  'gets',
  'you',
  'almost',
  'a',
  'whole',
  'second',
  'gram',
  'for',
  '&',
  'lt',
  ';',
  '#',
  '&',
  'gt',
  ';'],
 ['k',
  'fyi',
  'x',
  'has',
  'a',
  'ride',
  'early',
  'tomorrow',
  'morning',
  'but',
  'he',
  "'s",
  'crashing',
  'at',
  'our',
  'place',
  'tonight'],
 ['wow',
  '.',
  'i',
  'never',
  'realized',
  'that',
  'you',
  'were',
  'so',
  'embarassed',
  'by',
  'your',
  'accomodations',
  '.',
  'i',
  'thought',
  'you',
  'liked',
  'it',
  ',',
  'since',
  'i',
  'was',
  'doing',
  'the',
  'best',
  'i',
  'could',
  'and',
  'you',
  'always',
  'seemed',
  'so',
  'happy',
  'about',
  '``',
  'the',
  'cave',
  "''",
  '.',
  'i',
  "'m",
  'sorry',
  'i',
  'did',
  "n't",
  'and',
  'do',
  "n't",
  'have',
  'more',
  'to',
  'give',
  '.',
  'i',
  "'m",
  'sorry',
  'i',
  'offered',
  '.',
  'i',
  "'m",
  'sorry',
  'your',
  'room',
  'was',
  'so',
  'embarassing',
  '.'],
 ['sms',
  '.',
  'ac',
  'sptv',
  ':',
  'the',
  'new',
  'jersey',
  'devils',
  'and',
  'the',
  'detroit',
  'red',
  'wings',
  'play',
  'ice',
  'hockey',
  '.',
  'correct',
  'or',
  'incorrect',
  '?',
  'end',
  '?',
  'reply',
  'end',
  'sptv'],
 ['do',
  'you',
  'know',
  'what',
  'mallika',
  'sherawat',
  'did',
  'yesterday',
  '?',
  'find',
  'out',
  'now',
  '@',
  '&',
  'lt',
  ';',
  'url',
  '&',
  'gt',
  ';'],
 ['congrats',
  '!',
  '1',
  'year',
  'special',
  'cinema',
  'pass',
  'for',
  '2',
  'is',
  'yours',
  '.',
  'call',
  '09061209465',
  'now',
  '!',
  'c',
  'suprman',
  'v',
  ',',
  'matrix3',
  ',',
  'starwars3',
  ',',
  'etc',
  'all',
  '4',
  'free',
  '!',
  'bx420-ip4-5we',
  '.',
  '150pm',
  '.',
  'dont',
  'miss',
  'out',
  '!'],
 ['sorry', ',', 'i', "'ll", 'call', 'later', 'in', 'meeting', '.'],
 ['tell', 'where', 'you', 'reached'],
 ['yes', '..', 'gauti', 'and', 'sehwag', 'out', 'of', 'odi', 'series', '.'],
 ['your',
  'gon',
  'na',
  'have',
  'to',
  'pick',
  'up',
  'a',
  '$',
  '1',
  'burger',
  'for',
  'yourself',
  'on',
  'your',
  'way',
  'home',
  '.',
  'i',
  'ca',
  "n't",
  'even',
  'move',
  '.',
  'pain',
  'is',
  'killing',
  'me',
  '.'],
 ['ha',
  'ha',
  'ha',
  'good',
  'joke',
  '.',
  'girls',
  'are',
  'situation',
  'seekers',
  '.'],
 ['its', 'a', 'part', 'of', 'checking', 'iq'],
 ['sorry',
  'my',
  'roommates',
  'took',
  'forever',
  ',',
  'it',
  'ok',
  'if',
  'i',
  'come',
  'by',
  'now',
  '?'],
 ['ok',
  'lar',
  'i',
  'double',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'already',
  'he',
  'said',
  'wun',
  'cut',
  'v',
  'short',
  '.',
  'he',
  'said',
  'will',
  'cut',
  'until',
  'i',
  'look',
  'nice',
  '.'],
 ['as',
  'a',
  'valued',
  'customer',
  ',',
  'i',
  'am',
  'pleased',
  'to',
  'advise',
  'you',
  'that',
  'following',
  'recent',
  'review',
  'of',
  'your',
  'mob',
  'no',
  '.',
  'you',
  'are',
  'awarded',
  'with',
  'a',
  '£1500',
  'bonus',
  'prize',
  ',',
  'call',
  '09066364589'],
 ['today',
  'is',
  '``',
  'song',
  'dedicated',
  'day',
  '..',
  "''",
  'which',
  'song',
  'will',
  'u',
  'dedicate',
  'for',
  'me',
  '?',
  'send',
  'this',
  'to',
  'all',
  'ur',
  'valuable',
  'frnds',
  'but',
  'first',
  'rply',
  'me',
  '...'],
 ['urgent',
  'ur',
  'awarded',
  'a',
  'complimentary',
  'trip',
  'to',
  'eurodisinc',
  'trav',
  ',',
  'aco',
  '&',
  'entry41',
  'or',
  '£1000',
  '.',
  'to',
  'claim',
  'txt',
  'dis',
  'to',
  '87121',
  '18+6',
  '*',
  '£1.50',
  '(',
  'morefrmmob',
  '.',
  'shracomorsglsuplt',
  ')',
  '10',
  ',',
  'ls1',
  '3aj'],
 ['did',
  'you',
  'hear',
  'about',
  'the',
  'new',
  '``',
  'divorce',
  'barbie',
  "''",
  '?',
  'it',
  'comes',
  'with',
  'all',
  'of',
  'ken',
  "'s",
  'stuff',
  '!'],
 ['i', 'plane', 'to', 'give', 'on', 'this', 'month', 'end', '.'],
 ['wah',
  'lucky',
  'man',
  '...',
  'then',
  'can',
  'save',
  'money',
  '...',
  'hee',
  '...'],
 ['finished', 'class', 'where', 'are', 'you', '.'],
 ['hi',
  'babe',
  'im',
  'at',
  'home',
  'now',
  'wan',
  'na',
  'do',
  'something',
  '?',
  'xx'],
 ['k',
  '..',
  'k',
  ':',
  ')',
  'where',
  'are',
  'you',
  '?',
  'how',
  'did',
  'you',
  'performed',
  '?'],
 ['u', 'can', 'call', 'me', 'now', '...'],
 ['i',
  'am',
  'waiting',
  'machan',
  '.',
  'call',
  'me',
  'once',
  'you',
  'free',
  '.'],
 ['thats',
  'cool',
  '.',
  'i',
  'am',
  'a',
  'gentleman',
  'and',
  'will',
  'treat',
  'you',
  'with',
  'dignity',
  'and',
  'respect',
  '.'],
 ['i',
  'like',
  'you',
  'peoples',
  'very',
  'much',
  ':',
  ')',
  'but',
  'am',
  'very',
  'shy',
  'pa',
  '.'],
 ['does',
  'not',
  'operate',
  'after',
  '&',
  'lt',
  ';',
  '#',
  '&',
  'gt',
  ';',
  'or',
  'what'],
 ['its',
  'not',
  'the',
  'same',
  'here',
  '.',
  'still',
  'looking',
  'for',
  'a',
  'job',
  '.',
  'how',
  'much',
  'do',
  'ta',
  "'s",
  'earn',
  'there',
  '.'],
 ['sorry', ',', 'i', "'ll", 'call', 'later'],
 ['k.', 'did', 'you', 'call', 'me', 'just', 'now', 'ah', '?'],
 ['ok', 'i', 'am', 'on', 'the', 'way', 'to', 'home', 'hi', 'hi'],
 ['you', 'will', 'be', 'in', 'the', 'place', 'of', 'that', 'man'],
 ['yup', 'next', 'stop', '.'],
 ['i',
  'call',
  'you',
  'later',
  ',',
  'do',
  "n't",
  'have',
  'network',
  '.',
  'if',
  'urgnt',
  ',',
  'sms',
  'me',
  '.'],
 ['for',
  'real',
  'when',
  'u',
  'getting',
  'on',
  'yo',
  '?',
  'i',
  'only',
  'need',
  '2',
  'more',
  'tickets',
  'and',
  'one',
  'more',
  'jacket',
  'and',
  'i',
  "'m",
  'done',
  '.',
  'i',
  'already',
  'used',
  'all',
  'my',
  'multis',
  '.'],
 ['yes',
  'i',
  'started',
  'to',
  'send',
  'requests',
  'to',
  'make',
  'it',
  'but',
  'pain',
  'came',
  'back',
  'so',
  'i',
  "'m",
  'back',
  'in',
  'bed',
  '.',
  'double',
  'coins',
  'at',
  'the',
  'factory',
  'too',
  '.',
  'i',
  'got',
  'ta',
  'cash',
  'in',
  'all',
  'my',
  'nitros',
  '.'],
 ['i', "'m", 'really', 'not', 'up', 'to', 'it', 'still', 'tonight', 'babe'],
 ['ela',
  'kano.',
  ',',
  'il',
  'download',
  ',',
  'come',
  'wen',
  'ur',
  'free',
  '..'],
 ['yeah',
  'do',
  '!',
  'don',
  '‘',
  't',
  'stand',
  'to',
  'close',
  'tho-',
  'you',
  '‘',
  'll',
  'catch',
  'something',
  '!'],
 ['sorry',
  'to',
  'be',
  'a',
  'pain',
  '.',
  'is',
  'it',
  'ok',
  'if',
  'we',
  'meet',
  'another',
  'night',
  '?',
  'i',
  'spent',
  'late',
  'afternoon',
  'in',
  'casualty',
  'and',
  'that',
  'means',
  'i',
  'have',
  "n't",
  'done',
  'any',
  'of',
  'y',
  'stuff42moro',
  'and',
  'that',
  'includes',
  'all',
  'my',
  'time',
  'sheets',
  'and',
  'that',
  '.',
  'sorry',
  '.'],
 ['smile',
  'in',
  'pleasure',
  'smile',
  'in',
  'pain',
  'smile',
  'when',
  'trouble',
  'pours',
  'like',
  'rain',
  'smile',
  'when',
  'sum1',
  'hurts',
  'u',
  'smile',
  'becoz',
  'someone',
  'still',
  'loves',
  'to',
  'see',
  'u',
  'smiling',
  '!',
  '!'],
 ['please',
  'call',
  'our',
  'customer',
  'service',
  'representative',
  'on',
  '0800',
  '169',
  '6031',
  'between',
  '10am-9pm',
  'as',
  'you',
  'have',
  'won',
  'a',
  'guaranteed',
  '£1000',
  'cash',
  'or',
  '£5000',
  'prize',
  '!'],
 ['havent',
  'planning',
  'to',
  'buy',
  'later',
  '.',
  'i',
  'check',
  'already',
  'lido',
  'only',
  'got',
  '530',
  'show',
  'in',
  'e',
  'afternoon',
  '.',
  'u',
  'finish',
  'work',
  'already',
  '?'],
 ['your',
  'free',
  'ringtone',
  'is',
  'waiting',
  'to',
  'be',
  'collected',
  '.',
  'simply',
  'text',
  'the',
  'password',
  '``',
  'mix',
  "''",
  'to',
  '85069',
  'to',
  'verify',
  '.',
  'get',
  'usher',
  'and',
  'britney',
  '.',
  'fml',
  ',',
  'po',
  'box',
  '5249',
  ',',
  'mk17',
  '92h',
  '.',
  '450ppw',
  '16'],
 ['watching', 'telugu', 'movie', '..', 'wat', 'abt', 'u', '?'],
 ['i',
  'see',
  '.',
  'when',
  'we',
  'finish',
  'we',
  'have',
  'loads',
  'of',
  'loans',
  'to',
  'pay'],
 ['hi',
  '.',
  'wk',
  'been',
  'ok',
  '-',
  'on',
  'hols',
  'now',
  '!',
  'yes',
  'on',
  'for',
  'a',
  'bit',
  'of',
  'a',
  'run',
  '.',
  'forgot',
  'that',
  'i',
  'have',
  'hairdressers',
  'appointment',
  'at',
  'four',
  'so',
  'need',
  'to',
  'get',
  'home',
  'n',
  'shower',
  'beforehand',
  '.',
  'does',
  'that',
  'cause',
  'prob',
  'for',
  'u',
  '?',
  "''"],
 ['i', 'see', 'a', 'cup', 'of', 'coffee', 'animation'],
 ['please',
  'do',
  "n't",
  'text',
  'me',
  'anymore',
  '.',
  'i',
  'have',
  'nothing',
  'else',
  'to',
  'say',
  '.'],
 ['okay',
  'name',
  'ur',
  'price',
  'as',
  'long',
  'as',
  'its',
  'legal',
  '!',
  'wen',
  'can',
  'i',
  'pick',
  'them',
  'up',
  '?',
  'y',
  'u',
  'ave',
  'x',
  'ams',
  'xx'],
 ['i',
  "'m",
  'still',
  'looking',
  'for',
  'a',
  'car',
  'to',
  'buy',
  '.',
  'and',
  'have',
  'not',
  'gone',
  '4the',
  'driving',
  'test',
  'yet',
  '.'],
 ['as',
  'per',
  'your',
  'request',
  "'melle",
  'melle',
  '(',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  ')',
  "'",
  'has',
  'been',
  'set',
  'as',
  'your',
  'callertune',
  'for',
  'all',
  'callers',
  '.',
  'press',
  '*',
  '9',
  'to',
  'copy',
  'your',
  'friends',
  'callertune'],

## **OBSERVATIONS**

1.  The above list is a list of all the tokenized sentences obtained from the message column of the dataframe.

2.  This can be fed as an input into the Word2Vec model.

## **Step 5: Train the Word2Vec model**

In [203]:
### Train the Word2Vec model

model = Word2Vec(
    sentences   =    res            ,
    vector_size =     50            ,
    window      =     5             ,
    min_count   =     1             ,
    sg          =     0             ,
    workers     =     1
)

## **OBSERVATIONS:**

1.  The model of Word2Vec has been created with the help of the following parameters:-----

    (a.)  sentences = list of the tokenized sentences

    (b.)  vector_size = size of the dense dimensional embedded vector

    (c.)  window = 5 ---->  5 context input neighbors need to be considered for determining the target

    (d.)  min_count = 1 ------>  Minimum number of frequency needed for the dictionary

    (e.)sg = 0 ------------> determines the type of the model architecture.

            (i.)  If sg = 0 ----------->  Model architecture is CBOW.


2.The CBOW model is trained.

In [204]:
model

## **Step 6: Get the vocabulary from the model**

In [205]:
#### Get the vocabulary

vocabulary = model.wv.key_to_index

In [206]:
vocabulary

{'.': 0,
 'i': 1,
 'to': 2,
 'you': 3,
 ',': 4,
 '?': 5,
 'a': 6,
 '!': 7,
 'the': 8,
 '...': 9,
 'u': 10,
 'and': 11,
 '&': 12,
 'is': 13,
 'in': 14,
 'me': 15,
 ';': 16,
 'my': 17,
 'it': 18,
 ':': 19,
 'for': 20,
 '..': 21,
 'your': 22,
 'of': 23,
 'have': 24,
 'call': 25,
 'that': 26,
 'do': 27,
 'on': 28,
 ')': 29,
 'are': 30,
 "'s": 31,
 'now': 32,
 '2': 33,
 'so': 34,
 'not': 35,
 'but': 36,
 'or': 37,
 'can': 38,
 'at': 39,
 'we': 40,
 "'m": 41,
 'ur': 42,
 'if': 43,
 'get': 44,
 'will': 45,
 'be': 46,
 'with': 47,
 'just': 48,
 "n't": 49,
 'no': 50,
 'this': 51,
 'gt': 52,
 'lt': 53,
 '*': 54,
 'up': 55,
 'how': 56,
 'when': 57,
 'what': 58,
 '4': 59,
 '#': 60,
 'from': 61,
 'go': 62,
 'free': 63,
 'all': 64,
 'out': 65,
 'know': 66,
 'got': 67,
 'ok': 68,
 'like': 69,
 'good': 70,
 'was': 71,
 'then': 72,
 '-': 73,
 'come': 74,
 "'ll": 75,
 'there': 76,
 'he': 77,
 'am': 78,
 'its': 79,
 'time': 80,
 'only': 81,
 'day': 82,
 'love': 83,
 'want': 84,
 'send': 85,
 'text': 86,
 'as': 87,
 'one': 88,
 'ü': 89,
 'going': 90,
 'by': 91,
 'txt': 92,
 'need': 93,
 'about': 94,
 'did': 95,
 'home': 96,
 'lor': 97,
 'r': 98,
 'sorry': 99,
 'see': 100,
 'still': 101,
 'stop': 102,
 'she': 103,
 'today': 104,
 'back': 105,
 'n': 106,
 'da': 107,
 'our': 108,
 'reply': 109,
 'dont': 110,
 'hi': 111,
 "''": 112,
 'mobile': 113,
 'tell': 114,
 'new': 115,
 '``': 116,
 'later': 117,
 'take': 118,
 'any': 119,
 'they': 120,
 'think': 121,
 'please': 122,
 'been': 123,
 'phone': 124,
 'her': 125,
 'pls': 126,
 'has': 127,
 'who': 128,
 'some': 129,
 'here': 130,
 '(': 131,
 'dear': 132,
 'where': 133,
 'well': 134,
 'night': 135,
 'week': 136,
 'oh': 137,
 'much': 138,
 'great': 139,
 'an': 140,
 'k': 141,
 'claim': 142,
 'hey': 143,
 'c': 144,
 'him': 145,
 'hope': 146,
 'more': 147,
 'happy': 148,
 'wat': 149,
 'too': 150,
 'na': 151,
 'had': 152,
 'd': 153,
 'give': 154,
 'should': 155,
 'way': 156,
 'work': 157,
 'make': 158,
 'number': 159,
 'yes': 160,
 'wan': 161,
 'right': 162,
 'prize': 163,
 'say': 164,
 'message': 165,
 "'ve": 166,
 'already': 167,
 'tomorrow': 168,
 "'re": 169,
 'after': 170,
 'said': 171,
 't': 172,
 'ask': 173,
 'doing': 174,
 'amp': 175,
 'yeah': 176,
 'really': 177,
 'im': 178,
 'msg': 179,
 'why': 180,
 'them': 181,
 'would': 182,
 'life': 183,
 '1': 184,
 'meet': 185,
 'e': 186,
 'miss': 187,
 'last': 188,
 'very': 189,
 'babe': 190,
 'let': 191,
 'morning': 192,
 'cos': 193,
 'thanks': 194,
 'anything': 195,
 'lol': 196,
 'cash': 197,
 'find': 198,
 'won': 199,
 'every': 200,
 'win': 201,
 'care': 202,
 'also': 203,
 'pick': 204,
 'sure': 205,
 'sent': 206,
 'keep': 207,
 'something': 208,
 '3': 209,
 'contact': 210,
 'nokia': 211,
 'over': 212,
 'cant': 213,
 'again': 214,
 'b': 215,
 'urgent': 216,
 'before': 217,
 'gud': 218,
 'buy': 219,
 'could': 220,
 'us': 221,
 'wait': 222,
 'even': 223,
 'someone': 224,
 'his': 225,
 'thing': 226,
 'were': 227,
 'first': 228,
 'feel': 229,
 'next': 230,
 'off': 231,
 'went': 232,
 'which': 233,
 'ca': 234,
 'around': 235,
 'tonight': 236,
 'many': 237,
 'service': 238,
 'late': 239,
 'money': 240,
 'place': 241,
 'soon': 242,
 'gon': 243,
 'sleep': 244,
 'ya': 245,
 'nice': 246,
 'always': 247,
 'customer': 248,
 'per': 249,
 'leave': 250,
 'chat': 251,
 '....': 252,
 'down': 253,
 'other': 254,
 'friends': 255,
 'dun': 256,
 'told': 257,
 'wish': 258,
 'things': 259,
 'waiting': 260,
 'x': 261,
 'try': 262,
 'haha': 263,
 'help': 264,
 'may': 265,
 'coming': 266,
 'friend': 267,
 'thk': 268,
 'people': 269,
 'yet': 270,
 'guaranteed': 271,
 'same': 272,
 'year': 273,
 'getting': 274,
 'hello': 275,
 'done': 276,
 'fine': 277,
 'name': 278,
 'use': 279,
 'tone': 280,
 'best': 281,
 'v': 282,
 'heart': 283,
 'mins': 284,
 'holiday': 285,
 'does': 286,
 'live': 287,
 'lunch': 288,
 'god': 289,
 'smile': 290,
 'special': 291,
 'thought': 292,
 'class': 293,
 'bit': 294,
 'man': 295,
 'talk': 296,
 'person': 297,
 'few': 298,
 'draw': 299,
 'never': 300,
 'being': 301,
 'stuff': 302,
 "'": 303,
 'line': 304,
 'ill': 305,
 'job': 306,
 'meeting': 307,
 'sms': 308,
 'trying': 309,
 'yup': 310,
 'mind': 311,
 'having': 312,
 'u.': 313,
 'better': 314,
 'long': 315,
 'y': 316,
 'cool': 317,
 'thats': 318,
 'finish': 319,
 's': 320,
 'cs': 321,
 'ready': 322,
 'dat': 323,
 'min': 324,
 'account': 325,
 'end': 326,
 'car': 327,
 'enjoy': 328,
 'days': 329,
 'chance': 330,
 'than': 331,
 'because': 332,
 'sir': 333,
 'play': 334,
 'latest': 335,
 '1st': 336,
 '5': 337,
 'luv': 338,
 'lot': 339,
 'guess': 340,
 'nothing': 341,
 'box': 342,
 'yo': 343,
 'awarded': 344,
 'check': 345,
 '@': 346,
 'half': 347,
 'eat': 348,
 'word': 349,
 'receive': 350,
 'lar': 351,
 'world': 352,
 'start': 353,
 'big': 354,
 'guys': 355,
 'liao': 356,
 'another': 357,
 '‘': 358,
 'problem': 359,
 'shit': 360,
 'into': 361,
 'house': 362,
 'girl': 363,
 'shows': 364,
 'birthday': 365,
 'real': 366,
 'sweet': 367,
 'camera': 368,
 'ever': 369,
 'jus': 370,
 'po': 371,
 '£1000': 372,
 'dinner': 373,
 'quite': 374,
 'might': 375,
 'ok.': 376,
 'landline': 377,
 '150ppm': 378,
 'ah': 379,
 'room': 380,
 'watching': 381,
 'wont': 382,
 'xxx': 383,
 'probably': 384,
 'two': 385,
 'watch': 386,
 'called': 387,
 'offer': 388,
 'aight': 389,
 'once': 390,
 'month': 391,
 'cost': 392,
 'speak': 393,
 'early': 394,
 'princess': 395,
 'den': 396,
 'actually': 397,
 'minutes': 398,
 'plan': 399,
 'bed': 400,
 'hear': 401,
 'weekend': 402,
 'pay': 403,
 'remember': 404,
 'kiss': 405,
 'bad': 406,
 'sat': 407,
 'dunno': 408,
 'made': 409,
 'shall': 410,
 'baby': 411,
 'shopping': 412,
 'video': 413,
 'thanx': 414,
 'reach': 415,
 'easy': 416,
 'forgot': 417,
 'between': 418,
 'part': 419,
 'maybe': 420,
 'look': 421,
 'left': 422,
 '>': 423,
 'fun': 424,
 'apply': 425,
 'office': 426,
 'orange': 427,
 'hour': 428,
 'didnt': 429,
 'everything': 430,
 'face': 431,
 'leh': 432,
 'boy': 433,
 'little': 434,
 'dis': 435,
 '2nd': 436,
 'code': 437,
 'dad': 438,
 'fuck': 439,
 'put': 440,
 'working': 441,
 'tv': 442,
 'those': 443,
 'award': 444,
 'looking': 445,
 '+': 446,
 'ringtone': 447,
 'bus': 448,
 'enough': 449,
 'selected': 450,
 'network': 451,
 'town': 452,
 'while': 453,
 'asked': 454,
 'collect': 455,
 'evening': 456,
 'tmr': 457,
 'missing': 458,
 'i.ll': 459,
 'without': 460,
 'anyway': 461,
 'afternoon': 462,
 'most': 463,
 'thank': 464,
 'details': 465,
 'true': 466,
 'hav': 467,
 'xmas': 468,
 'sexy': 469,
 '150p': 470,
 'bt': 471,
 'join': 472,
 'school': 473,
 'must': 474,
 'says': 475,
 '16': 476,
 'came': 477,
 'since': 478,
 'calls': 479,
 'wanted': 480,
 "'d": 481,
 'though': 482,
 'wif': 483,
 'until': 484,
 '6': 485,
 'collection': 486,
 'g': 487,
 'bring': 488,
 'texts': 489,
 'tones': 490,
 'guy': 491,
 'wake': 492,
 'important': 493,
 'able': 494,
 'okay': 495,
 'abt': 496,
 'means': 497,
 'pain': 498,
 'goes': 499,
 'entry': 500,
 'plus': 501,
 'gift': 502,
 'away': 503,
 'wot': 504,
 'plz': 505,
 'decimal': 506,
 'years': 507,
 'mail': 508,
 'juz': 509,
 'price': 510,
 'wk': 511,
 'show': 512,
 'wen': 513,
 'missed': 514,
 'times': 515,
 '16+': 516,
 'wife': 517,
 'de': 518,
 'attempt': 519,
 'bored': 520,
 'weekly': 521,
 '18': 522,
 'else': 523,
 'havent': 524,
 'pa': 525,
 'mob': 526,
 'hair': 527,
 'yesterday': 528,
 'saw': 529,
 'messages': 530,
 'wo': 531,
 'till': 532,
 'update': 533,
 'rate': 534,
 'lei': 535,
 'makes': 536,
 'online': 537,
 'these': 538,
 'stay': 539,
 'dude': 540,
 'hurt': 541,
 'music': 542,
 '500': 543,
 'oso': 544,
 'til': 545,
 'haf': 546,
 'food': 547,
 'worry': 548,
 'making': 549,
 'run': 550,
 '$': 551,
 'yours': 552,
 'uk': 553,
 'alright': 554,
 'valid': 555,
 'dreams': 556,
 '£100': 557,
 'goin': 558,
 'family': 559,
 'sch': 560,
 'either': 561,
 'change': 562,
 'friendship': 563,
 'book': 564,
 'hot': 565,
 'coz': 566,
 'top': 567,
 'answer': 568,
 'test': 569,
 'driving': 570,
 'double': 571,
 'yourself': 572,
 'delivery': 573,
 're': 574,
 'tried': 575,
 'ard': 576,
 '9': 577,
 'sad': 578,
 '8007': 579,
 'wants': 580,
 'feeling': 581,
 'together': 582,
 'game': 583,
 'lose': 584,
 'sae': 585,
 'beautiful': 586,
 'tot': 587,
 'full': 588,
 'wid': 589,
 'nite': 590,
 'shop': 591,
 'order': 592,
 'todays': 593,
 'address': 594,
 'movie': 595,
 'comes': 596,
 'trip': 597,
 'bonus': 598,
 'words': 599,
 'colour': 600,
 'hours': 601,
 'question': 602,
 'o': 603,
 'await': 604,
 'drive': 605,
 'saying': 606,
 '7': 607,
 'eve': 608,
 'huh': 609,
 'chikku': 610,
 'calling': 611,
 'charge': 612,
 'club': 613,
 'ring': 614,
 'vouchers': 615,
 'walk': 616,
 'happen': 617,
 'noe': 618,
 'both': 619,
 'sleeping': 620,
 'id': 621,
 'story': 622,
 'believe': 623,
 '£2000': 624,
 'points': 625,
 'old': 626,
 'mean': 627,
 '£5000': 628,
 'smiling': 629,
 'm': 630,
 'date': 631,
 'set': 632,
 'brother': 633,
 '£1.50': 634,
 'rite': 635,
 'email': 636,
 'pics': 637,
 'thinking': 638,
 '£500': 639,
 'post': 640,
 'okie': 641,
 '86688': 642,
 'wil': 643,
 'minute': 644,
 'awesome': 645,
 'gr8': 646,
 'leaving': 647,
 'private': 648,
 '18+': 649,
 'busy': 650,
 'don': 651,
 'finished': 652,
 'took': 653,
 'congrats': 654,
 'tomo': 655,
 'aft': 656,
 'http': 657,
 'pounds': 658,
 'auction': 659,
 'drop': 660,
 'anyone': 661,
 'neva': 662,
 'mum': 663,
 'mine': 664,
 'gd': 665,
 'land': 666,
 'head': 667,
 'unsubscribe': 668,
 '750': 669,
 'angry': 670,
 'smoke': 671,
 'everyone': 672,
 'taking': 673,
 'services': 674,
 'cause': 675,
 'close': 676,
 'started': 677,
 'ta': 678,
 '10': 679,
 'forget': 680,
 'news': 681,
 'final': 682,
 'alone': 683,
 'knw': 684,
 'voucher': 685,
 'pub': 686,
 'whatever': 687,
 'simple': 688,
 'dating': 689,
 'drink': 690,
 'poly': 691,
 'sister': 692,
 'games': 693,
 'card': 694,
 'choose': 695,
 'company': 696,
 'break': 697,
 'found': 698,
 'touch': 699,
 'sis': 700,
 'worth': 701,
 'each': 702,
 'parents': 703,
 'lots': 704,
 'whats': 705,
 'open': 706,
 'msgs': 707,
 'expires': 708,
 'statement': 709,
 '12hrs': 710,
 'search': 711,
 'lucky': 712,
 'second': 713,
 'lesson': 714,
 '100': 715,
 'available': 716,
 'hows': 717,
 'pic': 718,
 'loving': 719,
 'sun': 720,
 'kind': 721,
 'bout': 722,
 'mobileupd8': 723,
 'lets': 724,
 'far': 725,
 'anytime': 726,
 'takes': 727,
 'sounds': 728,
 'college': 729,
 'boytoy': 730,
 'carlos': 731,
 'needs': 732,
 'frnd': 733,
 'hard': 734,
 'type': 735,
 'identifier': 736,
 'happened': 737,
 'gone': 738,
 'prob': 739,
 'girls': 740,
 '08000930705': 741,
 'decided': 742,
 'saturday': 743,
 'mom': 744,
 'tho': 745,
 'smth': 746,
 'ha': 747,
 'wonderful': 748,
 'pobox': 749,
 'info': 750,
 'winner': 751,
 'treat': 752,
 'chennai': 753,
 'party': 754,
 'wrong': 755,
 'mates': 756,
 'lovely': 757,
 'weeks': 758,
 'fast': 759,
 'sea': 760,
 'pretty': 761,
 'outside': 762,
 'nope': 763,
 'visit': 764,
 'fucking': 765,
 '08000839402': 766,
 '150p/msg': 767,
 'light': 768,
 'read': 769,
 'hold': 770,
 'congratulations': 771,
 'tel': 772,
 'secret': 773,
 'oredi': 774,
 'goodmorning': 775,
 'darlin': 776,
 'mrng': 777,
 'finally': 778,
 'wit': 779,
 'content': 780,
 'hand': 781,
 'ni8': 782,
 'operator': 783,
 'hit': 784,
 'used': 785,
 'xx': 786,
 'camcorder': 787,
 'crazy': 788,
 'nyt': 789,
 'least': 790,
 'mate': 791,
 'b4': 792,
 '…': 793,
 'snow': 794,
 'listen': 795,
 'offers': 796,
 'fri': 797,
 'frm': 798,
 'cum': 799,
 'welcome': 800,
 'ten': 801,
 '£250': 802,
 'reason': 803,
 'project': 804,
 'jay': 805,
 'fone': 806,
 '.....': 807,
 'unlimited': 808,
 'meant': 809,
 'case': 810,
 'thinks': 811,
 '10p': 812,
 'course': 813,
 'log': 814,
 'bank': 815,
 'fancy': 816,
 'their': 817,
 'yr': 818,
 'nt': 819,
 'player': 820,
 'mu': 821,
 'hmm': 822,
 'friday': 823,
 'frnds': 824,
 'whole': 825,
 'telling': 826,
 'seeing': 827,
 'hungry': 828,
 'credit': 829,
 'freemsg': 830,
 'wkly': 831,
 '||': 832,
 'father': 833,
 'gas': 834,
 'w': 835,
 'enter': 836,
 'earlier': 837,
 'knew': 838,
 'understand': 839,
 'mayb': 840,
 'sex': 841,
 'opt': 842,
 '£350': 843,
 'area': 844,
 'happiness': 845,
 'yar': 846,
 '800': 847,
 '2003': 848,
 'within': 849,
 'savamob': 850,
 '8': 851,
 'pm': 852,
 'ass': 853,
 'phones': 854,
 'couple': 855,
 'talking': 856,
 'motorola': 857,
 'currently': 858,
 'txts': 859,
 'reading': 860,
 'christmas': 861,
 'lost': 862,
 'bslvyl': 863,
 'blue': 864,
 'dnt': 865,
 '87066': 866,
 'fr': 867,
 'side': 868,
 'march': 869,
 'ltd': 870,
 'age': 871,
 'quiz': 872,
 'numbers': 873,
 'caller': 874,
 'invited': 875,
 'felt': 876,
 'mah': 877,
 '0800': 878,
 'download': 879,
 'hee': 880,
 'cut': 881,
 'almost': 882,
 'valued': 883,
 'press': 884,
 'point': 885,
 'john': 886,
 'difficult': 887,
 'luck': 888,
 'grins': 889,
 'surprise': 890,
 'information': 891,
 'support': 892,
 'heard': 893,
 'extra': 894,
 'ugh': 895,
 'picking': 896,
 'ans': 897,
 'darren': 898,
 'gym': 899,
 'through': 900,
 'un-redeemed': 901,
 'ipod': 902,
 'park': 903,
 'doin': 904,
 'supposed': 905,
 'th': 906,
 'india': 907,
 'rental': 908,
 'seen': 909,
 'st': 910,
 'ago': 911,
 'die': 912,
 'ends': 913,
 'swing': 914,
 'questions': 915,
 'laptop': 916,
 'reveal': 917,
 'bcoz': 918,
 'semester': 919,
 'joy': 920,
 'tired': 921,
 'direct': 922,
 'sending': 923,
 'uncle': 924,
 'askd': 925,
 'computer': 926,
 'loads': 927,
 'complimentary': 928,
 'song': 929,
 'etc': 930,
 'correct': 931,
 'wow': 932,
 'charged': 933,
 'national': 934,
 'eh': 935,
 'mobiles': 936,
 'police': 937,
 'loved': 938,
 'feels': 939,
 'truth': 940,
 'sort': 941,
 'whenever': 942,
 'wonder': 943,
 'sell': 944,
 'paper': 945,
 'sound': 946,
 'noon': 947,
 'clean': 948,
 '£2,000': 949,
 '4.': 950,
 '2.': 951,
 'monday': 952,
 'asking': 953,
 'yep': 954,
 'rock': 955,
 'slow': 956,
 'discount': 957,
 'met': 958,
 'small': 959,
 'via': 960,
 'plans': 961,
 'pete': 962,
 'rest': 963,
 'somebody': 964,
 'wana': 965,
 'own': 966,
 'exam': 967,
 'rs': 968,
 'kate': 969,
 'orchard': 970,
 'bath': 971,
 'muz': 972,
 'hmmm': 973,
 'safe': 974,
 'wine': 975,
 'txting': 976,
 'dogging': 977,
 'match': 978,
 'entered': 979,
 'shower': 980,
 'rply': 981,
 'checking': 982,
 'move': 983,
 'pass': 984,
 'gets': 985,
 '=': 986,
 'crave': 987,
 'abiola': 988,
 'confirm': 989,
 'comin': 990,
 'eg': 991,
 'sunday': 992,
 'usf': 993,
 'comp': 994,
 'empty': 995,
 'fact': 996,
 'write': 997,
 '%': 998,
 'she.s': 999,
 ...}

## **OBSERVATIONS**

1.  Here we have obtained the list of all the vocabularies after getting trained from Word2Vec model.

## **Step 7: Get the word vector**

In [207]:
#### Get the vector form of the word 'easy'

model.wv['easy']

array([ 0.09734271, -0.01055117, -0.01710207, -0.03041005, -0.04830376,
       -0.1648974 ,  0.22502361,  0.3761735 , -0.21187302, -0.13272245,
        0.04628559, -0.31011316,  0.15573879,  0.12620212, -0.17804702,
        0.22563155,  0.20656124,  0.04704044, -0.3272515 , -0.24987622,
        0.12505724,  0.06921759,  0.50484574, -0.110344  ,  0.18428017,
        0.10418702, -0.06650363,  0.04961716, -0.27826208,  0.15405284,
        0.00287578, -0.0374819 ,  0.03847683, -0.04180386, -0.01649134,
        0.06086094,  0.2371307 , -0.02972472,  0.05957698, -0.08381695,
        0.24758384, -0.01027965, -0.02863646,  0.01659336,  0.4151543 ,
        0.07292053, -0.02229223, -0.20389405,  0.21386823,  0.12522535],
      dtype=float32)

In [208]:
#### Get the vector form of the word 'free'
model.wv['free']

array([ 0.50413895,  0.05331755,  0.18743967,  0.3283631 , -0.2111056 ,
       -0.39361933,  1.2648715 ,  1.5923188 , -1.1976776 , -0.4676762 ,
        0.3056324 , -1.5570214 ,  0.9978619 ,  0.30205086, -1.0110929 ,
        0.6423959 ,  1.1471316 ,  0.02725804, -1.4921259 , -1.4002966 ,
        0.9363259 ,  0.32259637,  2.6252425 , -0.6402094 ,  0.5346676 ,
        0.02925752, -0.41576242,  0.05053121, -1.2300285 ,  0.58581376,
        0.32910737, -0.01759705,  0.56483066,  0.03677833, -0.03192168,
        0.07478218,  0.60970646,  0.08529624,  0.04305375, -0.5105338 ,
        1.3178703 , -0.26613316, -0.17343721, -0.16297697,  1.4071605 ,
       -0.11222028,  0.330627  , -0.82567924,  0.9197642 ,  0.43713483],
      dtype=float32)

## **OBSERVATIONS**

1.  Here we have obtained the dense dimensional numerical vector of the size 50 for the word 'easy' and 'free'.

## **Step 8: Get the Vector Shape**

In [209]:
#### Get the shape of the vector

model.wv['easy'].shape

(50,)

In [210]:
model.wv['gets'].shape

(50,)

## **OBSERVATIONS:**

1.  The shape of the input vector is (50,).

## **Step 9: Get the most similar words w.r.to a particular word**

In [211]:
#### Get the most similar word w.r.to 'easy'
model.wv.most_similar('easy')

[('phone', 0.9965216517448425),
 ('more', 0.9959041476249695),
 ('between', 0.9958078265190125),
 ('chat', 0.9957349896430969),
 ('number', 0.9956907033920288),
 ('waiting', 0.99561607837677),
 ('thanks', 0.9955706000328064),
 ('fucking', 0.9954506158828735),
 ('off', 0.9954097867012024),
 ('with', 0.9953771829605103)]

## **OBSERVATIONS:**

1.  The above are the list of all the words that are similar to easy as their vector values are verymuch close to the vector representation value of 'easy'.

In [212]:
#### Get the most similar word w.r.to 'free'
model.wv.most_similar('free')

[('nokia', 0.9978139400482178),
 ('mobile', 0.9969006180763245),
 ('claim', 0.9961849451065063),
 ('txt', 0.995154619216919),
 ('latest', 0.9947271347045898),
 ('mobileupd8', 0.9938870072364807),
 ('camcorder', 0.993559718132019),
 ('orange', 0.9935161471366882),
 ('cash', 0.9933136105537415),
 ('entry', 0.993053674697876)]

## **OBSERVATIONS:**

1.  The above are the list of all the words that are similar to easy as their vector values are verymuch close to the vector representation value of 'free'.

## **Step 11: Get the Similarity between two words:**

In [213]:
#### Get the similarity between two words
model.wv.similarity('free','win')

np.float32(0.9730826)

## **OBSERVATIONS:**

1.  Here the similarity score between the two words ('free','win') is 0.97 which states that these two words are more identical with respect to each other.