#### To implement the Multiple Linear Regression based on the House Price dataset and perform Regression Evaluation Metrics


##### Step 1: Import all the necessary libraries

In [1199]:
import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns

from    sklearn.model_selection  import  train_test_split, KFold, GridSearchCV
from    sklearn.preprocessing    import  StandardScaler
from    sklearn.linear_model     import  LinearRegression, Ridge, Lasso, ElasticNet
from    sklearn.metrics          import  mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

#### Step 2: Load the Dataset

In [1200]:
df = pd.read_csv("Housing.csv")

In [1201]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

#### OBSERVATIONS:

1.  The above dataset explains about the house pricing details for each and every house records.

2.  The independent features used in the dataset ranges from area ......... furnishingstatus

3.  The dependent   feature is the price of the house.

#### Step 3: Perform the Data Exploration

In [1202]:
#### get the top five records in the dataset

df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [1203]:
#### get the bottom five records in the dataset

df.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [1204]:
#### get the total length of the dataset

print("Length of the dataset is:", len(df))

Length of the dataset is: 545

In [1205]:
#### get the shape of the dataset

print("Shape of the dataset is:", df.shape)

Shape of the dataset is: (545, 13)

In [1206]:
#### get the columns used in the dataset

df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [1207]:
#### get the information about each column in the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [1208]:
#### get the descriptive statistics about the columns used in the dataset

df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

#### OBSERVATIONS:

1.  It explains about the descriptive statistical information about each numerical column used in the dataset.

#### Step 4: Perform Feature Engineering

In [1209]:
cols = ['mainroad',	'guestroom',	'basement',	'hotwaterheating' ,'airconditioning', 'prefarea']


#### convert the categorical features into the numerical column by mapping them

for x in cols:
    df[x] = df[x].map({"yes":1, "no":0})

In [1210]:
from sklearn.preprocessing  import LabelEncoder

#### create an object for Label Encoder

label = LabelEncoder()

#### transform the inputs for "furnishingstatus"

df['furnishingstatus'] = label.fit_transform(df['furnishingstatus'])

In [1211]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0

In [1212]:
#### Check for any NULL record in the dataset

df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

#### OBSERVATIONS:

1.  There are no NULL records in the dataset.

In [1213]:
#### To check for the duplicate records in the dataset

df[df.duplicated()]

Empty DataFrame
Columns: [price, area, bedrooms, bathrooms, stories, mainroad, guestroom, basement, hotwaterheating, airconditioning, parking, prefarea, furnishingstatus]
Index: []

#### OBSERVATIONS:

1.  There are no duplicate records in the dataset

#### Step 5: Divide the dataset into independent and dependent features

In [1214]:
#### independent features

X = df.drop(columns='price',axis=1)

print(X)

     area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
0    7420         4          2        3         1          0         0
1    8960         4          4        4         1          0         0
2    9960         3          2        2         1          0         1
3    7500         4          2        2         1          0         1
4    7420         4          1        2         1          1         1
..    ...       ...        ...      ...       ...        ...       ...
540  3000         2          1        1         1          0         1
541  2400         3          1        1         0          0         0
542  3620         2          1        1         1          0         0
543  2910         3          1        1         0          0         0
544  3850         3          1        2         1          0         0

     hotwaterheating  airconditioning  parking  prefarea  furnishingstatus
0                  0                1        2         1                 0
1                  0                1        3         0                 0
2                  0                0        2         1                 1
3                  0                1        3         1                 0
4                  0                1        2         0                 0
..               ...              ...      ...       ...               ...
540                0                0        2         0                 2
541                0                0        0         0                 1
542                0                0        0         0                 2
543                0                0        0         0                 0
544                0                0        0         0                 2

[545 rows x 12 columns]

In [1215]:
#### dependent features

Y = df['price']

print(Y)

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

#### Step 6: Divide the independent and dependent features into training and testing data

In [1216]:
from  sklearn.model_selection  import  train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [1217]:
X_train

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
46,6000,3,2,4,1,0,0,0,1,1,0,0
93,7200,3,2,1,1,0,1,0,1,3,0,1
335,3816,2,1,1,1,0,1,0,1,2,0,0
412,2610,3,1,2,1,0,1,0,0,0,1,2
471,3750,3,1,2,1,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
71,6000,4,2,4,1,0,0,0,1,0,0,2
106,5450,4,2,1,1,0,1,0,1,0,1,1
270,4500,3,2,3,1,0,0,1,0,1,0,0
435,4040,2,1,1,1,0,0,0,0,0,0,2
102,5500,3,2,4,1,1,0,0,1,1,0,1

In [1218]:
X_test

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
316,5900,4,2,2,0,0,1,0,0,1,0,2
77,6500,3,2,3,1,0,0,0,1,0,1,0
360,4040,2,1,1,1,0,0,0,0,0,0,1
90,5000,3,1,2,1,0,0,0,1,0,0,1
493,3960,3,1,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
15,6000,4,1,2,1,0,1,0,0,2,0,1
357,6930,4,1,2,0,0,0,0,0,1,0,0
39,6000,4,2,4,1,0,0,0,1,1,0,1
54,6000,3,2,2,1,1,0,0,1,1,0,1
155,6100,3,2,1,1,0,1,0,0,2,1,0

In [1219]:
print("Shape of the input training data is:", X_train.shape)
print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (436, 12)
Shape of the input testing  data is: (109, 12)

In [1220]:
Y_train

46     7525000
93     6300000
335    3920000
412    3430000
471    3010000
        ...
71     6755000
106    6160000
270    4340000
435    3290000
102    6195000
Name: price, Length: 436, dtype: int64

In [1221]:
Y_test

316    4060000
77     6650000
360    3710000
90     6440000
493    2800000
        ...
15     9100000
357    3773000
39     7910000
54     7350000
155    5530000
Name: price, Length: 109, dtype: int64

In [1222]:
print("Shape of the output training data is:", Y_train.shape)
print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (436,)
Shape of the output testing  data is: (109,)

#### Step 7: Perform Hyper Parameter Tuning using GridSearchCV

In [1223]:
#### create the pipeline

from  sklearn.pipeline  import  Pipeline

#### create an object for Pipeline

pipeline = Pipeline([
    ("sc"         ,        StandardScaler())             ,
    ("ridge"      ,        Ridge())
])

In [1224]:
#### define the parameter grid

param_grid = {
    "ridge__alpha"     :         [0.01, 0.1,    1,  10, 100]
}

In [1225]:
#### perform the KFold Cross Validation

cv = KFold(n_splits=5, shuffle=True, random_state=42)

In [1226]:
#### create an object for GridSearchCV

grid = GridSearchCV(
    pipeline                ,
    param_grid              ,
    cv          =    cv     ,
    scoring     =    'r2'
)

In [1227]:
##### using the object of GridSearchCV, train the model

grid.fit(X_train, Y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('sc', StandardScaler()),
                                       ('ridge', Ridge())]),
             param_grid={'ridge__alpha': [0.01, 0.1, 1, 10, 100]},
             scoring='r2')

In [1228]:
##### get the best parameters and estimators of the model

best_parameters = grid.best_params_

print("Best Parameters of the model is:", best_parameters)

Best Parameters of the model is: {'ridge__alpha': 10}

In [1229]:
best_estimator = grid.best_estimator_

print("Best Estimators of the model is:", best_estimator)

Best Estimators of the model is: Pipeline(steps=[('sc', StandardScaler()), ('ridge', Ridge(alpha=10))])

In [1230]:
#### predict the model

Y_pred_grid = best_estimator.predict(X_test)

In [1231]:
Y_pred_grid

array([5186078.49228468, 7215424.63436571, 3078154.87651011,
       4564276.36267827, 3359757.85705382, 3576607.92146009,
       5645455.60222503, 6405077.05048196, 2777902.87179176,
       2694752.0227472 , 9503465.29446023, 2843010.90212358,
       3197099.8043578 , 3356094.61027054, 3720294.56045208,
       5281326.70136989, 3003946.25786594, 4811920.14880486,
       4382034.14539347, 3531314.53526903, 5772707.35418599,
       5832334.89482507, 2777117.78847751, 4769574.85659592,
       5204265.00850656, 7466253.50180209, 3271884.98967863,
       5235969.77342821, 8126535.84227654, 3445786.52558435,
       6411381.18461757, 3368797.4458539 , 6722234.26601742,
       4160415.22407493, 3613826.60698904, 5775581.1678268 ,
       4783337.39322841, 4404361.85572548, 3231073.79950835,
       4652176.08857165, 4532713.68270606, 3549980.36349883,
       7196928.3217633 , 4039770.38636305, 3704717.46591658,
       4298421.41376399, 6667085.10501831, 4020326.6784457 ,
       3794646.18551731, 3463268.96204276, 7251626.98600655,
       2854142.69127538, 4378258.05057046, 4457035.53007701,
       3733460.20392492, 2743304.84332852, 7487232.7283714 ,
       2975254.39364738, 4211729.51229024, 2812029.57851455,
       4792232.1549622 , 3617006.57670886, 5091528.42020127,
       4239531.59249632, 4733319.00561727, 4625677.743725  ,
       7151324.02759622, 3496026.77014792, 5928064.19357442,
       6237019.33661184, 4783915.97068653, 5118454.14848309,
       4523916.5123144 , 7954471.82981903, 3558337.70576026,
       5453300.28225373, 3924424.03766745, 4654141.92222147,
       4835745.5164644 , 4271413.47932422, 7726671.49783901,
       4028465.79605597, 6490233.23521712, 5361541.03161157,
       2813411.65837634, 6802846.98750105, 2670288.60394225,
       3655731.09552716, 7971747.63982087, 8010467.87381188,
       3258731.80668764, 5933723.71241144, 3614788.74631585,
       3822973.23888674, 7611865.86479648, 4805770.72956321,
       5104775.54076875, 6410207.96332396, 4936058.66660376,
       5927271.47517195, 3834254.51373072, 6455253.92032793,
       3715124.33384501, 5929444.56134665, 4943890.26345396,
       4386731.07605915, 6983624.27676095, 6341226.7918968 ,
       6386995.42620725])

#### Step 8: Calculate the Slope and Intercept of the Model

In [1232]:
print("Slope of the model is:", best_estimator.named_steps['ridge'].coef_[0])

print("Intercept of the model is:", best_estimator.named_steps['ridge'].intercept_)

Slope of the model is: 509061.14076371345
Intercept of the model is: 4706527.385321101

#### Step 9: Perform the Regression Evaluation Metrics

In [1233]:
from  sklearn.metrics  import  mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

"================================Mean Absolute Error==========================================="

mae = mean_absolute_error(Y_test, Y_pred_grid)

print("Mean Absolute Error of the model is:", mae)

Mean Absolute Error of the model is: 978653.4031173647

In [1234]:
"================================Mean Squared Error==========================================="

mse = mean_squared_error(Y_test, Y_pred_grid)

print("Mean Squared Error of the model is:", mse)

Mean Squared Error of the model is: 1778081197208.694

In [1235]:
"=============================Root Mean Squared Error==========================================="

rmse = root_mean_squared_error(Y_test, Y_pred_grid)

print("Root Mean Squared Error of the model is:", rmse)

Root Mean Squared Error of the model is: 1333447.1107654378

In [1236]:
"=============================R2 Score========================================================="

r2 = r2_score(Y_test, Y_pred_grid)

print("R2 Score of the model is:", r2)

R2 Score of the model is: 0.648223071290926

In [1237]:
"=============================R2 adjusted========================================================="

n = X_test.shape[0]   #### Number of rows

p = X_test.shape[1]   #### Number of independent features


adjusted_r2 = 1-((1-r2)*(n-1))/(n-p-1)


print("Adjusted R2 Score of the model is:", adjusted_r2)

Adjusted R2 Score of the model is: 0.6042509552022919