#### To implement the Multiple Linear Regression based on the House Price dataset using Regularization techniques

##### Step 1: Import all the necessary libraries

In [518]:
import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns

from    sklearn.model_selection  import  train_test_split, StratifiedKFold, GridSearchCV
from    sklearn.preprocessing    import  StandardScaler
from    sklearn.linear_model     import  LinearRegression, Ridge, Lasso, ElasticNet
from    sklearn.metrics          import  mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

#### Step 2: Load the Dataset

In [519]:
df = pd.read_csv("Housing.csv")

In [520]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

#### OBSERVATIONS:

1.  The above dataset explains about the house pricing details for each and every house records.

2.  The independent features used in the dataset ranges from area ......... furnishingstatus

3.  The dependent   feature is the price of the house.

#### Step 3: Perform the Data Exploration

In [521]:
#### get the top five records in the dataset

df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [522]:
#### get the bottom five records in the dataset

df.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [523]:
#### get the length of the dataset

print("Length of the dataset is:", len(df))

Length of the dataset is: 545

In [524]:
#### get the shape of the dataset

print("Shape of the dataset is:", df.shape)

Shape of the dataset is: (545, 13)

In [525]:
#### get the columns used in the dataset

df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [526]:
#### get the information about the columns used in the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [527]:
#### get the descriptive summary statistics abou the columns used in the dataset

df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [528]:
df.describe(include='object')

,mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus
count,545,545,545,545,545,545,545
unique,2,2,2,2,2,2,3
top,yes,no,no,no,no,no,semi-furnished
freq,468,448,354,520,373,417,227

#### Step 4: Perform Feature Engineering and Data Cleaning

In [529]:
#### Convert all the categorical features into numerical values

cols = ['mainroad',	'guestroom','basement',	'hotwaterheating',	'airconditioning',	'prefarea']

for x in cols:
    df[x] = df[x].map({"yes":1,"no":0})

In [530]:
#### perform label encoding on the "furnishingstatus" column

from  sklearn.preprocessing import  LabelEncoder

#### create an object for LabelEncoder

label = LabelEncoder()

#### using the object for LabelEncoder, transform the inputs

df['furnishingstatus'] = label.fit_transform(df['furnishingstatus'])

In [531]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0

#### OBSERVATIONS:

1.  All the categorical features have been converted into the numerical features.

In [532]:
#### To check for the null records used in the dataset

df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

#### OBSERVATIONS:

1.  There are no NULL values used in the dataset.

In [533]:
#### To check for the duplicate records used in the dataset

df[df.duplicated()]

Empty DataFrame
Columns: [price, area, bedrooms, bathrooms, stories, mainroad, guestroom, basement, hotwaterheating, airconditioning, parking, prefarea, furnishingstatus]
Index: []

#### OBSERVATIONS:

1.  There are no duplicate records used in the dataset.

#### Step 5: Divide the dataset into independent and dependent features

In [534]:
#### independent features

X = df.drop(columns='price',axis=1)

print(X)

     area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
0    7420         4          2        3         1          0         0
1    8960         4          4        4         1          0         0
2    9960         3          2        2         1          0         1
3    7500         4          2        2         1          0         1
4    7420         4          1        2         1          1         1
..    ...       ...        ...      ...       ...        ...       ...
540  3000         2          1        1         1          0         1
541  2400         3          1        1         0          0         0
542  3620         2          1        1         1          0         0
543  2910         3          1        1         0          0         0
544  3850         3          1        2         1          0         0

     hotwaterheating  airconditioning  parking  prefarea  furnishingstatus
0                  0                1        2         1                 0
1                  0                1        3         0                 0
2                  0                0        2         1                 1
3                  0                1        3         1                 0
4                  0                1        2         0                 0
..               ...              ...      ...       ...               ...
540                0                0        2         0                 2
541                0                0        0         0                 1
542                0                0        0         0                 2
543                0                0        0         0                 0
544                0                0        0         0                 2

[545 rows x 12 columns]

In [535]:
#### dependent features

Y = df['price']

print(Y)

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

#### Step 6: Divide the independent and dependent features into training and testing data

In [536]:
from  sklearn.model_selection   import  train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [537]:
X_train

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
46,6000,3,2,4,1,0,0,0,1,1,0,0
93,7200,3,2,1,1,0,1,0,1,3,0,1
335,3816,2,1,1,1,0,1,0,1,2,0,0
412,2610,3,1,2,1,0,1,0,0,0,1,2
471,3750,3,1,2,1,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
71,6000,4,2,4,1,0,0,0,1,0,0,2
106,5450,4,2,1,1,0,1,0,1,0,1,1
270,4500,3,2,3,1,0,0,1,0,1,0,0
435,4040,2,1,1,1,0,0,0,0,0,0,2
102,5500,3,2,4,1,1,0,0,1,1,0,1

In [538]:
X_test

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
316,5900,4,2,2,0,0,1,0,0,1,0,2
77,6500,3,2,3,1,0,0,0,1,0,1,0
360,4040,2,1,1,1,0,0,0,0,0,0,1
90,5000,3,1,2,1,0,0,0,1,0,0,1
493,3960,3,1,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
15,6000,4,1,2,1,0,1,0,0,2,0,1
357,6930,4,1,2,0,0,0,0,0,1,0,0
39,6000,4,2,4,1,0,0,0,1,1,0,1
54,6000,3,2,2,1,1,0,0,1,1,0,1
155,6100,3,2,1,1,0,1,0,0,2,1,0

In [539]:
print("Shape of the input training data is:", X_train.shape)
print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (436, 12)
Shape of the input testing  data is: (109, 12)

In [540]:
Y_train

46     7525000
93     6300000
335    3920000
412    3430000
471    3010000
        ...
71     6755000
106    6160000
270    4340000
435    3290000
102    6195000
Name: price, Length: 436, dtype: int64

In [541]:
Y_test

316    4060000
77     6650000
360    3710000
90     6440000
493    2800000
        ...
15     9100000
357    3773000
39     7910000
54     7350000
155    5530000
Name: price, Length: 109, dtype: int64

In [542]:
print("Shape of the output training data is:", Y_train.shape)
print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (436,)
Shape of the output testing  data is: (109,)

#### Step 7: Perform Feature Scaling on the inputs

In [543]:
from    sklearn.preprocessing   import  StandardScaler

#### create an object for Standard Scaler

sc = StandardScaler()

#### using the object for Standard Scaler, transform the inputs

X_train_scaled = sc.fit_transform(X_train)

In [544]:
X_train_scaled

array([[ 0.38416819,  0.05527092,  1.53917323, ...,  0.36795665,
        -0.55262032, -1.40940148],
       [ 0.9291807 ,  0.05527092,  1.53917323, ...,  2.70998729,
        -0.55262032, -0.07931697],
       [-0.60775457, -1.28351359, -0.5579503 , ...,  1.53897197,
        -0.55262032, -1.40940148],
       ...,
       [-0.29709744,  0.05527092,  1.53917323, ...,  0.36795665,
        -0.55262032, -1.40940148],
       [-0.5060189 , -1.28351359, -0.5579503 , ..., -0.80305867,
        -0.55262032,  1.25076755],
       [ 0.15707965,  0.05527092,  1.53917323, ...,  0.36795665,
        -0.55262032, -0.07931697]])

In [545]:
X_test_scaled = sc.transform(X_test)

In [546]:
X_test_scaled

array([[ 0.33875048,  1.39405543,  1.53917323, ...,  0.36795665,
        -0.55262032,  1.25076755],
       [ 0.61125674,  0.05527092,  1.53917323, ..., -0.80305867,
         1.80956067, -1.40940148],
       [-0.5060189 , -1.28351359, -0.5579503 , ..., -0.80305867,
        -0.55262032, -0.07931697],
       ...,
       [ 0.38416819,  1.39405543,  1.53917323, ...,  0.36795665,
        -0.55262032, -0.07931697],
       [ 0.38416819,  0.05527092,  1.53917323, ...,  0.36795665,
        -0.55262032, -0.07931697],
       [ 0.4295859 ,  0.05527092,  1.53917323, ...,  1.53897197,
         1.80956067, -1.40940148]])

#### OBSERVATIONS:

1.  All the input features have been scaled in the same range between -1 to 1.

#### Step 8: Train the Regularization Techniques

In [547]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet

print("================================Ridge Regression=========================================================")

ridge = Ridge(alpha=0.1)


ridge.fit(X_train_scaled,Y_train)


#### predict the model

Y_pred_ridge = ridge.predict(X_test_scaled)

print(Y_pred_ridge)


#### Calculate the Slope and Intercept of the model

print("Slope of the model is:", ridge.coef_[0])
print("Intercept of the model is:", ridge.intercept_)


#### Evaluate the Regression Metrics

from    sklearn.metrics          import  mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

mae = mean_absolute_error(Y_test, Y_pred_ridge)
print("Mean Absolute Error of the model is:", mae)


mse = mean_squared_error(Y_test, Y_pred_ridge)
print("Mean Squared Error of the model is:", mse)


rmse = root_mean_squared_error(Y_test, Y_pred_ridge)
print("Root Mean Squared Error of the model is:", rmse)


r2 = r2_score(Y_test, Y_pred_ridge)
print("R2 Score of the model is:", r2)

================================Ridge Regression=========================================================
[5203507.063658   7256577.26230002 3062983.89654945 4559641.12517682
 3333209.89654651 3563219.48698322 5645471.05270151 6413892.97106666
 2756057.07369427 2669202.69857508 9569913.51862456 2827588.72523915
 3195696.61704477 3352296.52770861 3713941.13142618 5300884.92707306
 2988081.52678613 4810812.67601231 4383017.66117169 3525153.43517407
 5796014.95855357 5839925.78836607 2760385.50151057 4762662.94253438
 5204750.70948231 7515033.66943727 3254856.68244129 5236163.9917417
 8177988.17223865 3434282.59989767 6443586.35157254 3346238.94652221
 6742122.47553041 4154991.92431818 3589407.96649519 5787999.66248591
 4768526.106225   4391815.75461928 3217794.20334085 4638344.37948038
 4522270.87204183 3541372.75524926 7237713.19949901 4021704.37053373
 3702004.02393349 4298874.57937448 6704612.17090618 3993746.20253937
 3798144.75635084 3451935.47144641 7293560.14854454 2833121.84595932
 4378692.16666717 4467885.09538012 3714816.64707112 2718720.86342771
 7524069.6311144  2950691.32739127 4194774.5694902  2795991.42004746
 4801687.69823985 3618213.70789953 5091686.41099923 4248030.37088115
 4729999.40132313 4621033.57809851 7215173.90067575 3485214.369964
 5933761.43725601 6236592.30116972 4809649.48319958 5130789.59825315
 4527246.66122508 8006331.56451275 3544076.26654928 5462989.43485228
 3902668.6888995  4660992.61603899 4825482.02054796 4276747.27451458
 7753797.03494115 4008779.04215515 6500872.47290548 5386530.12507326
 2785630.77788248 6836012.59049503 2638880.409734   3634453.49367533
 8003745.86705447 8048016.52576288 3227894.13901679 5935157.44957645
 3605863.29151614 3817819.66815124 7631478.00699322 4775431.41564611
 5093610.19272453 6447051.7258047  4943371.68896528 5943759.46698806
 3810706.3827446  6457412.25269434 3701629.2946097  5960170.48835115
 4933248.89564354 4377232.07946149 7009072.99952717 6351362.00969104
 6409111.69572547]
Slope of the model is: 519182.4735741749
Intercept of the model is: 4706527.385321101
Mean Absolute Error of the model is: 979666.5287590962
Mean Squared Error of the model is: 1771808783138.1958
Root Mean Squared Error of the model is: 1331093.078315035
R2 Score of the model is: 0.6494640104340739

In [548]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet

print("================================Lasso Regression=========================================================")

lasso = Lasso(alpha=1.0)


lasso.fit(X_train_scaled,Y_train)


#### predict the model

Y_pred_lasso = lasso.predict(X_test_scaled)

print(Y_pred_lasso)


#### Calculate the Slope and Intercept of the model

print("Slope of the model is:", lasso.coef_[0])
print("Intercept of the model is:", lasso.intercept_)


#### Evaluate the Regression Metrics

from    sklearn.metrics          import  mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

maelasso = mean_absolute_error(Y_test, Y_pred_lasso)
print("Mean Absolute Error of the model is:", maelasso)


mselasso = mean_squared_error(Y_test, Y_pred_lasso)
print("Mean Squared Error of the model is:", mselasso)


rmselasso = root_mean_squared_error(Y_test, Y_pred_lasso)
print("Root Mean Squared Error of the model is:", rmselasso)


r2lasso = r2_score(Y_test, Y_pred_lasso)
print("R2 Score of the model is:", r2lasso)

================================Lasso Regression=========================================================
[5203692.30854035 7257001.4763281  3062831.29417677 4559592.35326798
 3332934.16023909 3563083.28958015 5645465.85403071 6413976.32340207
 2755834.71638129 2668941.88035625 9570595.55689713 2827434.73842416
 3195689.88259198 3352265.67052659 3713880.37298779 5301089.84587383
 2987922.46971143 4810800.44961636 4383031.89400366 3525094.68316018
 5796257.93492853 5839998.35194096 2760217.86808729 4762588.30066343
 5204754.88677588 7515539.60766323 3254682.81118268 5236163.02248132
 8178518.82892635 3434167.73452076 6443919.21384534 3346006.56873122
 6742322.73940872 4154938.23436265 3589154.25109    5788125.68859704
 4768368.60671211 4391683.80539784 3217660.36483786 4638197.07033632
 4522161.25895084 3541286.4608791  7238133.58290021 4021516.32392909
 3701981.18404669 4298881.23233822 6705002.71401677 3993467.30335143
 3798187.85528932 3451822.59561974 7293994.95305363 2832908.10811385
 4378699.44767334 4468003.52299568 3714624.4751273  2718470.10060448
 7524446.15130387 2950439.50241982 4194597.36669719 2795831.01693244
 4801788.72980135 3618233.42405461 5091685.89087559 4248123.65116339
 4729963.89954492 4620978.88984682 7215843.38309397 3485107.16517457
 5933818.66431445 6236577.24849255 4809923.97298426 5130919.57137951
 4527284.10841801 8006865.71933679 3543929.6465546  5463082.11238822
 3902442.01175505 4661064.01861274 4825371.18559169 4276805.22969477
 7754068.87627956 4008573.91228695 6500974.57445006 5386794.5234975
 2785345.43492575 6836354.68786066 2638556.51161333 3634233.22608193
 8004068.46419916 8048391.97079662 3227574.83750655 5935165.30310429
 3605774.51280406 3817770.01299507 7631671.39364218 4775105.73093217
 5093490.2975645  6447436.38348639 4943449.14552935 5943927.73735457
 3810461.03129406 6457424.19739531 3701492.29800018 5960491.91650621
 4933135.97913153 4377134.39129205 7009332.90200669 6351459.70996246
 6409337.88878201]
Slope of the model is: 519287.9012524485
Intercept of the model is: 4706527.385321101
Mean Absolute Error of the model is: 979680.0187766452
Mean Squared Error of the model is: 1771752886890.6372
Root Mean Squared Error of the model is: 1331072.081778683
R2 Score of the model is: 0.6494750689899618

In [549]:
from sklearn.linear_model import Ridge, Lasso, ElasticNet

print("================================Elastic Net Regression=========================================================")

elasticnet = ElasticNet(alpha=0.1,l1_ratio=0.5)


elasticnet.fit(X_train_scaled,Y_train)


#### predict the model

Y_pred_elasticnet = elasticnet.predict(X_test_scaled)

print(Y_pred_elasticnet)


#### Calculate the Slope and Intercept of the model

print("Slope of the model is:", elasticnet.coef_[0])
print("Intercept of the model is:", elasticnet.intercept_)


#### Evaluate the Regression Metrics

from    sklearn.metrics          import  mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

maeelasticnet = mean_absolute_error(Y_test, Y_pred_elasticnet)
print("Mean Absolute Error of the model is:", maeelasticnet)


mseelasticnet = mean_squared_error(Y_test, Y_pred_elasticnet)
print("Mean Squared Error of the model is:", mseelasticnet)


rmseelasticnet = root_mean_squared_error(Y_test, Y_pred_elasticnet)
print("Root Mean Squared Error of the model is:", rmseelasticnet)


r2elasticnet = r2_score(Y_test, Y_pred_elasticnet)
print("R2 Score of the model is:", r2elasticnet)

================================Elastic Net Regression=========================================================
[5167273.12126177 7169013.86120206 3095749.30758633 4569205.57294818
 3389211.90100761 3591739.48944624 5644343.73505313 6394063.83869334
 2802804.93334829 2723803.80440599 9427973.00597782 2861046.72723127
 3199674.51838007 3361894.22045186 3728390.81988879 5259423.98741244
 3022581.91870679 4812867.85009603 4381747.58447149 3538881.26866694
 5747034.67482282 5822935.3778918  2796611.72268639 4777097.99501442
 5203667.48310181 7411905.0930164  3291458.51227865 5235395.46818609
 8068768.38391502 3459406.93437107 6375346.66299549 3394187.05590589
 6698917.37028014 4166789.14868524 3640862.76723681 5761028.66957068
 4799475.87622519 4418141.95755085 3246225.79374305 4666821.27880635
 4543970.9609177  3559864.17240068 7150926.84238245 4059836.37080885
 3708447.07010084 4298003.83770033 6625342.8586336  4049390.0257195
 3791623.84550054 3476845.43850187 7204708.63234464 2878192.60483397
 4378105.66279174 4445965.16647909 3754594.19907969 2771282.22880748
 7445225.73452055 3003092.06420762 4230297.0041916  2830750.97070841
 4782224.87966395 3616587.63257384 5090843.45582392 4230901.87162299
 4736876.85072433 4630369.42617892 7081654.78858768 3509085.71670094
 5921469.45650718 6235947.60080345 4756522.82016782 5105129.81276585
 4520540.93599622 7895914.45380945 3574296.99718043 5441548.34937878
 3948540.90362173 4646456.86463278 4846290.8199135  4265646.91743679
 7694797.55473299 4050280.38448207 6477128.30546933 5334820.74161898
 2844830.64953598 6765398.79439434 2705475.56728503 3679533.28895588
 7934450.55409291 7966740.85534207 3293344.04047749 5931000.5107605
 3625270.29470115 3829188.52371563 7587929.87394596 4837729.95161845
 5116662.43715857 6369388.03116549 4928268.90235761 5908387.39875023
 3860366.6868761  6450966.59455961 3730750.94473714 5895542.05449131
 4955522.17932088 4397330.66965742 6954467.01277714 6328440.32116211
 6361892.12436831]
Slope of the model is: 497796.43279447814
Intercept of the model is: 4706527.385321101
Mean Absolute Error of the model is: 978136.4582175559
Mean Squared Error of the model is: 1786840747461.21
Root Mean Squared Error of the model is: 1336727.62650482
R2 Score of the model is: 0.64649007524466

#### Step 9: Predict the price of the house based on the given sample data using Regulaization techniques

In [550]:
df.iloc[[0]]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0

In [551]:
X.iloc[[0]]

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,7420,4,2,3,1,0,0,0,1,2,1,0

In [552]:
print("===================================Ridge Regression===================================================")

#### define the sample data
sample = X.iloc[[0]]

#### scale the sample data

scaled_data = sc.transform(sample)
print(scaled_data)


#### perform the prediction on the data 
prediction = ridge.predict(scaled_data)
print("Price of the house using Ridge Regression is:", prediction)

===================================Ridge Regression===================================================
[[ 1.02909966  1.39405543  1.53917323  1.42092939  0.40715525 -0.46677307
  -0.74642003 -0.23052136  1.50124327  1.53897197  1.80956067 -1.40940148]]
Price of the house using Ridge Regression is: [8003745.86705447]

In [553]:
print("===================================Ridge Regression===================================================")

#### define the sample data
sample = X.iloc[[0]]

#### scale the sample data

scaled_data = sc.transform(sample)
print(scaled_data)


#### perform the prediction on the data 
prediction = lasso.predict(scaled_data)
print("Price of the house using Lasso Regression is:", prediction)

===================================Ridge Regression===================================================
[[ 1.02909966  1.39405543  1.53917323  1.42092939  0.40715525 -0.46677307
  -0.74642003 -0.23052136  1.50124327  1.53897197  1.80956067 -1.40940148]]
Price of the house using Lasso Regression is: [8004068.46419916]

In [554]:
print("===================================Elastic Net Regression===================================================")

#### define the sample data
sample = X.iloc[[0]]

#### scale the sample data

scaled_data = sc.transform(sample)
print(scaled_data)


#### perform the prediction on the data 
prediction = elasticnet.predict(scaled_data)
print("Price of the house using Elastic Net Regression is:", prediction)

===================================Elastic Net Regression===================================================
[[ 1.02909966  1.39405543  1.53917323  1.42092939  0.40715525 -0.46677307
  -0.74642003 -0.23052136  1.50124327  1.53897197  1.80956067 -1.40940148]]
Price of the house using Elastic Net Regression is: [7934450.55409291]