#### **BackPropogation**

1.  Backpropogation refers to the technique used in the neural networks that is ued to compute the gradients of the loss function with respect to the weights and bias using the chain rule and then updating them using gradient descent to minimize the error.


#### **Simple Neural Network**

Input Layer (30 features)

        ↓

Hidden Layer (5 neurons, ReLU)

        ↓

Output Layer (1 neuron, Sigmoid)



#### **Step 1: Import all the necessary libraries**

In [668]:
import  numpy               as    np
import  pandas              as    pd
import  matplotlib.pyplot   as    plt
import  seaborn             as    sns

from    sklearn.datasets         import load_breast_cancer
from    sklearn.model_selection  import train_test_split
from    sklearn.preprocessing    import StandardScaler

#### **Step 2: Load and prepare dataset**

In [669]:
#### extract the data
data = load_breast_cancer()

#### using the data, construct the dataframe
df = pd.DataFrame(data.data, columns=data.feature_names)

#### Adding the target to the dataframe
df['target'] = data.target

df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

In [670]:
#### divide the dataset into independent and dependent features

#### independent features
X = df.drop(columns='target',axis=1)
print(X)

     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840
1          20.57         17.77          132.90     1326.0          0.08474
2          19.69         21.25          130.00     1203.0          0.10960
3          11.42         20.38           77.58      386.1          0.14250
4          20.29         14.34          135.10     1297.0          0.10030
..           ...           ...             ...        ...              ...
564        21.56         22.39          142.00     1479.0          0.11100
565        20.13         28.25          131.20     1261.0          0.09780
566        16.60         28.08          108.30      858.1          0.08455
567        20.60         29.33          140.10     1265.0          0.11780
568         7.76         24.54           47.92      181.0          0.05263

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419
1             0.07864         0.08690              0.07017         0.1812
2             0.15990         0.19740              0.12790         0.2069
3             0.28390         0.24140              0.10520         0.2597
4             0.13280         0.19800              0.10430         0.1809
..                ...             ...                  ...            ...
564           0.11590         0.24390              0.13890         0.1726
565           0.10340         0.14400              0.09791         0.1752
566           0.10230         0.09251              0.05302         0.1590
567           0.27700         0.35140              0.15200         0.2397
568           0.04362         0.00000              0.00000         0.1587

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33
1                   0.05667  ...        24.990          23.41
2                   0.05999  ...        23.570          25.53
3                   0.09744  ...        14.910          26.50
4                   0.05883  ...        22.540          16.67
..                      ...  ...           ...            ...
564                 0.05623  ...        25.450          26.40
565                 0.05533  ...        23.690          38.25
566                 0.05648  ...        18.980          34.12
567                 0.07016  ...        25.740          39.42
568                 0.05884  ...         9.456          30.37

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560
1             158.80      1956.0           0.12380            0.18660
2             152.50      1709.0           0.14440            0.42450
3              98.87       567.7           0.20980            0.86630
4             152.20      1575.0           0.13740            0.20500
..               ...         ...               ...                ...
564           166.10      2027.0           0.14100            0.21130
565           155.00      1731.0           0.11660            0.19220
566           126.70      1124.0           0.11390            0.30940
567           184.60      1821.0           0.16500            0.86810
568            59.16       268.6           0.08996            0.06444

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601
1             0.2416                0.1860          0.2750
2             0.4504                0.2430          0.3613
3             0.6869                0.2575          0.6638
4             0.4000                0.1625          0.2364
..               ...                   ...             ...
564           0.4107                0.2216          0.2060
565           0.3215                0.1628          0.2572
566           0.3403                0.1418          0.2218
567           0.9387                0.2650          0.4087
568           0.0000                0.0000          0.2871

     worst fractal dimension
0                    0.11890
1                    0.08902
2                    0.08758
3                    0.17300
4                    0.07678
..                       ...
564                  0.07115
565                  0.06637
566                  0.07820
567                  0.12400
568                  0.07039

[569 rows x 30 columns]

In [671]:
#### dependent features
Y = df['target']
print(Y)

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: target, Length: 569, dtype: int64

In [672]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42,stratify=Y)

In [673]:
X_train

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
546,10.32,16.35,65.31,324.9,0.09434,0.04994,0.01012,0.005495,0.1885,0.06201,...,11.25,21.77,71.12,384.9,0.1285,0.08842,0.04384,0.02381,0.2681,0.07399
432,20.18,19.54,133.80,1250.0,0.11330,0.14890,0.21330,0.125900,0.1724,0.06053,...,22.03,25.07,146.00,1479.0,0.1665,0.29420,0.53080,0.21730,0.3032,0.08075
174,10.66,15.15,67.49,349.6,0.08792,0.04302,0.00000,0.000000,0.1928,0.05975,...,11.54,19.20,73.20,408.3,0.1076,0.06791,0.00000,0.00000,0.2710,0.06164
221,13.56,13.90,88.59,561.3,0.10510,0.11920,0.07860,0.044510,0.1962,0.06303,...,14.98,17.13,101.10,686.6,0.1376,0.26980,0.25770,0.09090,0.3065,0.08177
289,11.37,18.89,72.17,396.0,0.08713,0.05008,0.02399,0.021730,0.2013,0.05955,...,12.36,26.14,79.29,459.3,0.1118,0.09708,0.07529,0.06203,0.3267,0.06994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,15.28,22.41,98.92,710.6,0.09057,0.10520,0.05375,0.032630,0.1727,0.06317,...,17.80,28.03,113.80,973.1,0.1301,0.32990,0.36300,0.12260,0.3175,0.09772
300,19.53,18.90,129.50,1217.0,0.11500,0.16420,0.21970,0.106200,0.1792,0.06552,...,25.93,26.24,171.10,2053.0,0.1495,0.41160,0.61210,0.19800,0.2968,0.09929
509,15.46,23.95,103.80,731.3,0.11830,0.18700,0.20300,0.085200,0.1807,0.07083,...,17.11,36.33,117.70,909.4,0.1732,0.49670,0.59110,0.21630,0.3013,0.10670
230,17.05,19.08,113.40,895.0,0.11410,0.15720,0.19100,0.109000,0.2131,0.06325,...,19.59,24.89,133.50,1189.0,0.1703,0.39340,0.50180,0.25430,0.3109,0.09061
474,10.88,15.62,70.41,358.9,0.10070,0.10690,0.05115,0.015710,0.1861,0.06837,...,11.94,19.35,80.78,433.1,0.1332,0.38980,0.33650,0.07966,0.2581,0.10800

In [674]:
X_test

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
256,19.55,28.77,133.60,1207.0,0.09260,0.20630,0.17840,0.11440,0.1893,0.06232,...,25.05,36.27,178.60,1926.0,0.1281,0.53290,0.4251,0.19410,0.2818,0.10050
428,11.13,16.62,70.47,381.1,0.08151,0.03834,0.01369,0.01370,0.1511,0.06148,...,11.68,20.29,74.35,421.1,0.1030,0.06219,0.0458,0.04044,0.2383,0.07083
501,13.82,24.49,92.33,595.9,0.11620,0.16810,0.13570,0.06759,0.2275,0.07237,...,16.01,32.94,106.00,788.0,0.1794,0.39660,0.3381,0.15210,0.3651,0.11830
363,16.50,18.29,106.60,838.1,0.09686,0.08468,0.05862,0.04835,0.1495,0.05593,...,18.13,25.45,117.20,1009.0,0.1338,0.16790,0.1663,0.09123,0.2394,0.06469
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.45,26.40,166.10,2027.0,0.1410,0.21130,0.4107,0.22160,0.2060,0.07115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,20.26,23.03,132.40,1264.0,0.09078,0.13130,0.14650,0.08683,0.2095,0.05649,...,24.22,31.59,156.10,1750.0,0.1190,0.35390,0.4098,0.15730,0.3689,0.08368
128,15.10,16.39,99.58,674.5,0.11500,0.18070,0.11380,0.08534,0.2001,0.06467,...,16.11,18.33,105.90,762.6,0.1386,0.28830,0.1960,0.14230,0.2590,0.07779
257,15.32,17.27,103.20,713.3,0.13350,0.22840,0.24480,0.12420,0.2398,0.07596,...,17.73,22.66,119.80,928.8,0.1765,0.45030,0.4429,0.22290,0.3258,0.11910
228,12.62,23.97,81.35,496.4,0.07903,0.07529,0.05438,0.02036,0.1514,0.06019,...,14.20,31.31,90.67,624.0,0.1227,0.34540,0.3911,0.11800,0.2826,0.09585
488,11.68,16.17,75.49,420.5,0.11280,0.09263,0.04279,0.03132,0.1853,0.06401,...,13.32,21.59,86.57,549.8,0.1526,0.14770,0.1490,0.09815,0.2804,0.08024

In [675]:
print("Shape of the input training data is:", X_train.shape)
print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (455, 30)
Shape of the input testing  data is: (114, 30)

In [676]:
Y_train

546    1
432    0
174    1
221    1
289    1
      ..
184    0
300    0
509    0
230    0
474    1
Name: target, Length: 455, dtype: int64

In [677]:
Y_test

256    0
428    1
501    0
363    1
564    0
      ..
95     0
128    1
257    0
228    1
488    1
Name: target, Length: 114, dtype: int64

In [678]:
#### Convert Y_train and Y_test into column vectors immediately after train-test split
Y_train=Y_train.values.reshape(-1,1)

In [679]:
Y_train

array([[1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1]])

In [680]:
Y_test=Y_test.values.reshape(-1,1)

In [681]:
Y_test

array([[0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [682]:
print("Shape of the output training data is:", Y_train.shape)
print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (455, 1)
Shape of the output testing  data is: (114, 1)

In [683]:
#### Perform feature scaling on the inputs
from sklearn.preprocessing import StandardScaler

#### create an object for Standard Scaler
sc = StandardScaler()

#### using the object of standard scaler, transform the inputs
X_train = sc.fit_transform(X_train)
X_test  = sc.transform(X_test)

In [684]:
X_train

array([[-1.07200079, -0.6584246 , -1.0880801 , ..., -1.35052668,
        -0.35265805, -0.54138003],
       [ 1.74874285,  0.06650173,  1.75115682, ...,  1.54991557,
         0.19107787, -0.1737386 ],
       [-0.97473376, -0.93112416, -0.99770871, ..., -1.70744192,
        -0.307734  , -1.21303263],
       ...,
       [ 0.39844772,  1.06867262,  0.50751384, ...,  1.53492543,
         0.16164487,  1.23754763],
       [ 0.85331409, -0.0380331 ,  0.9054796 , ...,  2.10455077,
         0.31035897,  0.36249578],
       [-0.91179628, -0.82431683, -0.87666079, ..., -0.51332734,
        -0.50756857,  1.30824791]])

In [685]:
X_test

array([[ 1.56851278,  2.16401585,  1.74286587, ...,  1.20214432,
        -0.14043064,  0.90036171],
       [-0.84027641, -0.5970672 , -0.8741735 , ..., -1.10124064,
        -0.81429139, -0.71323608],
       [-0.07072262,  1.19138742,  0.03202768, ...,  0.57255843,
         1.14997397,  1.86841162],
       ...,
       [ 0.3583966 , -0.44935493,  0.48264098, ...,  1.63386036,
         0.54117564,  1.91191948],
       [-0.41401799,  1.07321761, -0.42314565, ...,  0.06139464,
        -0.1280378 ,  0.64747227],
       [-0.6829327 , -0.69932953, -0.66607058, ..., -0.23615965,
        -0.16211811, -0.20147486]])

#### **OBSERVATIONS:**

1.  Here feature scaling has been performed to bring all the inputs in the same scale range between 0 to 1.

#### **Step 3: Initialize the Parameters**

In [686]:
np.random.seed(42)

input_dim = X_train.shape[1]    ##### specifies the number of neurons in the input layer
hidden_dim = 5                  #### specifies  the number of neurons in the hidden layer
output_dim = 1                  #### specifies the number of neurons in the output layer

#### update the weights and bias
W1 =  np.random.randn(input_dim,hidden_dim)*0.01
b1 =  np.zeros((1,hidden_dim))

W2 =  np.random.randn(hidden_dim,output_dim)*0.01
b2 =  np.zeros((1,output_dim))

In [687]:
W1

array([[ 4.96714153e-03, -1.38264301e-03,  6.47688538e-03,
         1.52302986e-02, -2.34153375e-03],
       [-2.34136957e-03,  1.57921282e-02,  7.67434729e-03,
        -4.69474386e-03,  5.42560044e-03],
       [-4.63417693e-03, -4.65729754e-03,  2.41962272e-03,
        -1.91328024e-02, -1.72491783e-02],
       [-5.62287529e-03, -1.01283112e-02,  3.14247333e-03,
        -9.08024076e-03, -1.41230370e-02],
       [ 1.46564877e-02, -2.25776300e-03,  6.75282047e-04,
        -1.42474819e-02, -5.44382725e-03],
       [ 1.10922590e-03, -1.15099358e-02,  3.75698018e-03,
        -6.00638690e-03, -2.91693750e-03],
       [-6.01706612e-03,  1.85227818e-02, -1.34972247e-04,
        -1.05771093e-02,  8.22544912e-03],
       [-1.22084365e-02,  2.08863595e-03, -1.95967012e-02,
        -1.32818605e-02,  1.96861236e-03],
       [ 7.38466580e-03,  1.71368281e-03, -1.15648282e-03,
        -3.01103696e-03, -1.47852199e-02],
       [-7.19844208e-03, -4.60638771e-03,  1.05712223e-02,
         3.43618290e-03, -1.76304016e-02],
       [ 3.24083969e-03, -3.85082280e-03, -6.76922000e-03,
         6.11676289e-03,  1.03099952e-02],
       [ 9.31280119e-03, -8.39217523e-03, -3.09212376e-03,
         3.31263431e-03,  9.75545127e-03],
       [-4.79174238e-03, -1.85658977e-03, -1.10633497e-02,
        -1.19620662e-02,  8.12525822e-03],
       [ 1.35624003e-02, -7.20101216e-04,  1.00353290e-02,
         3.61636025e-03, -6.45119755e-03],
       [ 3.61395606e-03,  1.53803657e-02, -3.58260391e-04,
         1.56464366e-02, -2.61974510e-02],
       [ 8.21902504e-03,  8.70470682e-04, -2.99007350e-03,
         9.17607765e-04, -1.98756891e-02],
       [-2.19671888e-03,  3.57112572e-03,  1.47789404e-02,
        -5.18270218e-03, -8.08493603e-03],
       [-5.01757044e-03,  9.15402118e-03,  3.28751110e-03,
        -5.29760204e-03,  5.13267433e-03],
       [ 9.70775493e-04,  9.68644991e-03, -7.02053094e-03,
        -3.27662147e-03, -3.92108153e-03],
       [-1.46351495e-02,  2.96120277e-03,  2.61055272e-03,
         5.11345664e-05, -2.34587133e-03],
       [-1.41537074e-02, -4.20645323e-03, -3.42714517e-03,
        -8.02277269e-03, -1.61285712e-03],
       [ 4.04050857e-03,  1.88618590e-02,  1.74577813e-03,
         2.57550391e-03, -7.44459158e-04],
       [-1.91877122e-02, -2.65138754e-04,  6.02302099e-04,
         2.46324211e-02, -1.92360965e-03],
       [ 3.01547342e-03, -3.47117697e-04, -1.16867804e-02,
         1.14282281e-02,  7.51933033e-03],
       [ 7.91031947e-03, -9.09387455e-03,  1.40279431e-02,
        -1.40185106e-02,  5.86857094e-03],
       [ 2.19045563e-02, -9.90536325e-03, -5.66297730e-03,
         9.96513651e-04, -5.03475654e-03],
       [-1.55066343e-02,  6.85629748e-04, -1.06230371e-02,
         4.73592431e-03, -9.19424234e-03],
       [ 1.54993441e-02, -7.83253292e-03, -3.22061516e-03,
         8.13517217e-03, -1.23086432e-02],
       [ 2.27459935e-03,  1.30714275e-02, -1.60748323e-02,
         1.84633859e-03,  2.59882794e-03],
       [ 7.81822872e-03, -1.23695071e-02, -1.32045661e-02,
         5.21941566e-03,  2.96984673e-03]])

In [688]:
b1

array([[0., 0., 0., 0., 0.]])

In [689]:
W2

array([[ 0.00250493],
       [ 0.00346448],
       [-0.00680025],
       [ 0.00232254],
       [ 0.00293072]])

In [690]:
b2

array([[0.]])

#### **OBSERVATIONS:**

1.  As we know that there are three layers in this problem

    Input --------> hidden ------------> output

2.  So from the Input --------> hidden layer, we have W1 and b1 connecting the layers

3.  From hidden ----------> output layer, we have W2 and b2 connecting the layers

4.  We have first computed the values of Weights and the bias in both the layers

5.  Then the weights and the bias in both the layers have been updated to bring the predicted value equal to the actual value.

#### **Step 4: Define the Activation Functions**

In [691]:
def sigmoid(z):
  return(1/(1+np.exp(-z)))

def relu(z):
  return(np.maximum(0,z))

def relu_derivative(z):
  return(z > 0).astype(float)

#### **Step 5: Perform Forward Propogation**

In [692]:
#### perform the forward propogation
def forward(X):
  #### make some variables as global
  global Z1, A1, Z2, A2

  #### Perform forward propogation from the input to hidden layer
  Z1 = np.dot(X,W1) + b1
  A1 = relu(Z1)

  ### Perform forward propogation from the hidden to output layer
  Z2 = np.dot(A1,W2) + b2
  A2 = sigmoid(Z2)

  return(A2)

#### **Step 6: Compute the Loss Function**

In [693]:
#### define the loss function
def loss_function(Y_true, Y_pred):
  #### define the number of samples
  m = Y_true.shape[0]
  #### compute the loss function
  loss = -(1/m)*np.sum(
      Y_true*np.log(Y_pred + 1e-8) + (1-Y_true)*np.log(1-Y_pred + 1e-8)
  )
  return(loss)

#### **Step 7: Perform the BackPropogation**

In [694]:
#### perform the backpropogation
def backward(X, y, learning_rate=0.01):
    global W1, b1, W2, b2, Z1, A1, A2

    m = X.shape[0]

    # Output layer error
    dZ2 = A2 - y
    dW2 = np.dot(A1.T, dZ2) / m
    db2 = np.sum(dZ2, axis=0, keepdims=True) / m

    # Hidden layer error
    dA1 = np.dot(dZ2, W2.T)
    dZ1 = dA1 * relu_derivative(Z1)
    dW1 = np.dot(X.T, dZ1) / m
    db1 = np.sum(dZ1, axis=0, keepdims=True) / m

    # Update weights
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2

#### **Step 8: Perform the Training loop**

In [695]:
epochs = 1000
for i in range(epochs):
  #### perform the forward propogation
  Y_pred = forward(X_train)
  Y_pred = np.squeeze(Y_pred)
  #### compute the loss function
  loss = loss_function(Y_train, Y_pred)
  #### perform the backward propogation
  backward(X_train, Y_train)

  if (i % 100 == 0):
    print(f"Epoch {i}, Loss: {loss:.4f}")

Epoch 0, Loss: 315.3765
Epoch 100, Loss: 309.6240
Epoch 200, Loss: 306.0955
Epoch 300, Loss: 303.8378
Epoch 400, Loss: 302.2437
Epoch 500, Loss: 301.5314
Epoch 600, Loss: 305.9792
Epoch 700, Loss: 324.3390
Epoch 800, Loss: 354.8600
Epoch 900, Loss: 388.3822

#### **Step 9: Perform the prediction**

In [696]:
#### perform the prediction
def predict(X):
  Y_pred = forward(X)
  return(Y_pred > 0.5).astype(int)

#### **Step 10: Get the accuracy of the model**

In [697]:
Y_test_pred = predict(X_test)

accuracy = np.mean(Y_test_pred == Y_test)*100.0
print("Test Accuracy:", accuracy)

Test Accuracy: 93.85964912280701

#### **OBSERVATIONS:**

1.  The accuracy of the model using backpropogation is 93.85 which is very high.

2.  So the backpropogation process is completely working fine.