#### Perform Sentiment Analysis using Random Forest Classifier

1.  The main objective of this problem statement is

    (a.)    to understand the imdb movie review

    (b.)    to perform the sentiment analysis on the imdb movie review dataset using Random Forest Classifier

    (c.)    to perform text classification of the reviews and classify whether the movie reviews is having positive or negative sentiments.


#### Steps used in this Algorithm:---

1.  Import all the necessary libraries

2.  Download all the necessary NLTK lbraries

3.  Read the imdb Dataset

4.  Perform the Text Preprocessing Function

5.  Apply Cleaning

6.  Perform the Data Preprocessing Function

7.  Convert Text to Numerical Features (TF-IDF)

8.  Perform the Train-Test Split

9.  Train Random Forest Classifier Model

10. Make Predictions for the model

11. Evaluate the Model

12. Test with Custom Sentence

#### Step 1: Import all the necessary libraries

In [160]:
import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns

import  nltk

from   sklearn.feature_extraction.text  import TfidfVectorizer
from   sklearn.model_selection          import train_test_split
from   sklearn.preprocessing            import StandardScaler
from   sklearn.metrics                  import accuracy_score
from   sklearn.ensemble                 import RandomForestClassifier


from    nltk.tokenize          import word_tokenize
from    nltk.corpus            import stopwords
from    nltk.tokenize          import RegexpTokenizer

#### OBSERVATIONS:

1.  RandomForestClassifier -----------> 

        (a.)     It has multiple number of decision trees in it 
    
        (b.)     trained with nultiple decision trees 
        
        (c.)     provides the predicted output for each decision tree 
        
        (d.)     performs the majority voting on each decision tree 
        
        (e.)     at last provides the predicted output based on the voting process.

#### Step 2: Download all the necessary NLTK lbraries

In [161]:
#### Download the necessary resources for the nltk
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

#### OBSERVATIONS:

1.  Punkt_tab ----------> A pre defined tokenizer that divides the text into the tokens.

2.  stopwords ----------> It is used for the removal of the stop words.

#### Step 3: Read the imdb Dataset

In [162]:
#### Load the dataset
import pandas as pd

# Load full dataset (example path)
df = pd.read_csv("IMDB_Dataset.csv")

# Take a balanced sample
df_small = df.groupby("sentiment").sample(n=500, random_state=42)

# Reset index
df_small = df_small.reset_index(drop=True)

# Save reduced dataset
df_small.to_csv("IMDB_reduced.csv", index=False)

print(df_small.shape)

(1000, 2)

In [163]:
df = df_small

In [164]:
#### Load the dataset
df

                                                review sentiment
0    I was looking forward to seeing Bruce Willis i...  negative
1    Bugs Bunny accidentally ends up at the South P...  negative
2    I find it difficult to comprehend what makes v...  negative
3    It's been said several times - not least by me...  negative
4    New rule. Nobody is allowed to make any more Z...  negative
..                                                 ...       ...
995  A quite good film version of the novel, though...  positive
996  This movie is a great movie, however it is, as...  positive
997  Now this is what I'd call a good horror. With ...  positive
998  The story of a little girl who was driven once...  positive
999  This movie is good for what it is, and unprete...  positive

[1000 rows x 2 columns]

#### OBSERVATIONS:

1.  The above imdb movie dataset has 50000 records and has two columns

    (a.)    review ------------> It specifies the critics about the movie given.

    (b.)    sentiment ---------> whether the movie sentiment is positive or negative.

2.  The above dataset explains about the sentiment given for the critics of the imdb movies.

3.  We need to perform the sentiment analysis on the critics provided to the imdb movies and predict whether the movie sentiment is positive or negative.

#### Step 4: Perform the Text Preprocessing Function

In [165]:
#### define the function
def clean_review(text):
    #### convert the text into lower case
    text = text.lower()
    #### convert the text into words by performing word tokenization
    words = word_tokenize(text)
    #### convert the words in list into the text form
    words = ' '.join(words)
    #### create an object for RegexpTokenizer
    reg = RegexpTokenizer(r'\w+')
    #### apply the object of RegexpTokenizer to remove all the punctuations and the special symbols from the text
    ans = reg.tokenize(words)
    #### convert the text in lists to words
    ans = ' '.join(ans)
    return(ans)

#### OBSERVATIONS:

1.  The text preprocessing function has been defined that will clean all the reviews from the dataset using clean_text unction.

#### Step 5: Apply Cleaning

In [166]:
#### call the function
df['clean_review'] = df['review'].apply(clean_review)

In [167]:
df['clean_review']

0      i was looking forward to seeing bruce willis i...
1      bugs bunny accidentally ends up at the south p...
2      i find it difficult to comprehend what makes v...
3      it s been said several times not least by me t...
4      new rule nobody is allowed to make any more zo...
                             ...
995    a quite good film version of the novel though ...
996    this movie is a great movie however it is as m...
997    now this is what i d call a good horror with o...
998    the story of a little girl who was driven once...
999    this movie is good for what it is and unpreten...
Name: clean_review, Length: 1000, dtype: str

#### OBSERVATIONS:

1.  The clean_text function has been called that will clean the 'review' column and store the processed text in the 'clean_review' column of the dataset.

#### Step 6: Perform the Data Preprocessing Function

In [168]:
#### Map the labels 'positive' ---------> 1 and 'negative' ------------> 0

df['sentiment'] = df['sentiment'].map({'positive':1, 'negative':0})

In [169]:
df

,review,sentiment,clean_review
0,I was looking forward to seeing Bruce Willis i...,0,i was looking forward to seeing bruce willis i...
1,Bugs Bunny accidentally ends up at the South P...,0,bugs bunny accidentally ends up at the south p...
2,I find it difficult to comprehend what makes v...,0,i find it difficult to comprehend what makes v...
3,It's been said several times - not least by me...,0,it s been said several times not least by me t...
4,New rule. Nobody is allowed to make any more Z...,0,new rule nobody is allowed to make any more zo...
...,...,...,...
995,"A quite good film version of the novel, though...",1,a quite good film version of the novel though ...
996,"This movie is a great movie, however it is, as...",1,this movie is a great movie however it is as m...
997,Now this is what I'd call a good horror. With ...,1,now this is what i d call a good horror with o...
998,The story of a little girl who was driven once...,1,the story of a little girl who was driven once...
999,"This movie is good for what it is, and unprete...",1,this movie is good for what it is and unpreten...

#### OBSERVATIONS:

1.  The positive category of the sentiment column has been mapped to 1

2.  The negative category of the sentiment column has been mapped to 0.

In [170]:
#### Remove the column 'review' from the dataset
df.drop(columns='review',inplace=True)

In [171]:
df

     sentiment                                       clean_review
0            0  i was looking forward to seeing bruce willis i...
1            0  bugs bunny accidentally ends up at the south p...
2            0  i find it difficult to comprehend what makes v...
3            0  it s been said several times not least by me t...
4            0  new rule nobody is allowed to make any more zo...
..         ...                                                ...
995          1  a quite good film version of the novel though ...
996          1  this movie is a great movie however it is as m...
997          1  now this is what i d call a good horror with o...
998          1  the story of a little girl who was driven once...
999          1  this movie is good for what it is and unpreten...

[1000 rows x 2 columns]

In [172]:
#### Reorder the position of 'clean_review' and 'sentiment' in the dataframe
df=df[['clean_review','sentiment']]

In [173]:
df

                                          clean_review  sentiment
0    i was looking forward to seeing bruce willis i...          0
1    bugs bunny accidentally ends up at the south p...          0
2    i find it difficult to comprehend what makes v...          0
3    it s been said several times not least by me t...          0
4    new rule nobody is allowed to make any more zo...          0
..                                                 ...        ...
995  a quite good film version of the novel though ...          1
996  this movie is a great movie however it is as m...          1
997  now this is what i d call a good horror with o...          1
998  the story of a little girl who was driven once...          1
999  this movie is good for what it is and unpreten...          1

[1000 rows x 2 columns]

#### OBSERVATIONS:

1.  The new dataframe has been created that contains

    (a.)    clean_review -----------> all the clean preprocessed text data without any punctuations and special symbols.

    (b.)    sentiment    -----------> Positive as 1 and negative as 0.

#### Step 7: Convert Text to Numerical Features (TF-IDF)

In [174]:
from   sklearn.feature_extraction.text  import TfidfVectorizer

#### create an object for TfidfVectorizer
tfidf = TfidfVectorizer()

#### using the object for TfidfVectorizer, transform the text
X_sparse_matrix = tfidf.fit_transform(df['clean_review'])

In [175]:
X_sparse_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 133039 stored elements and shape (1000, 17612)>

#### OBSERVATIONS:

1.  The review text has been converted into the sparse matrix with 1000 words and 17612 vocabularies and it has 133039 non zero words that only stores the non zero words and their positions.

In [176]:
#### convert the sparse matrix into the numpy array
X_array = X_sparse_matrix.toarray()

In [177]:
X_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(1000, 17612))

#### OBSERVATIONS:

1.  The sparse matrix has been converted into numpy array for better view and visibility.

In [178]:
#### define the dependent variables
Y = df['sentiment']

In [179]:
Y

0      0
1      0
2      0
3      0
4      0
      ..
995    1
996    1
997    1
998    1
999    1
Name: sentiment, Length: 1000, dtype: int64

In [180]:
#### Determine the count of the output categories in the dependent variable
Y.value_counts()

sentiment
0    500
1    500
Name: count, dtype: int64

#### OBSERVATIONS:

1.  There are 500 positive sentiments and 500 negative sentiments in the dataset.

#### Step 8: Perform the Train-Test Split

In [181]:
#### Keep the input data in the form of sparse matrix

X_sparse_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 133039 stored elements and shape (1000, 17612)>

#### OBSERVATIONS:

1.  For splitting the data into training and testing, the data for the input must be in sparse matrix. This is because

    (a.)    converting it into the numpy array means converting the sparse matrix into dense matrix which makes the data more complex

    (b.)    It even causes more huge dense memory causing it for crashing.

In [182]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X_sparse_matrix, Y, test_size=0.2,random_state=42,stratify=Y)

In [183]:
X_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 107445 stored elements and shape (800, 17612)>

In [184]:
X_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 25594 stored elements and shape (200, 17612)>

In [185]:
print("Shape of the input training data is:", X_train.shape)
print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (800, 17612)
Shape of the input testing  data is: (200, 17612)

In [186]:
Y_train

859    1
299    0
759    1
397    0
794    1
      ..
139    0
956    1
643    1
237    0
737    1
Name: sentiment, Length: 800, dtype: int64

In [187]:
Y_test

907    1
293    0
217    0
54     0
614    1
      ..
836    1
512    1
343    0
594    1
752    1
Name: sentiment, Length: 200, dtype: int64

In [188]:
print("Shape of the output training data is:", Y_train.shape)
print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (800,)
Shape of the output testing  data is: (200,)

#### OBSERVATIONS:

1.  The dataset is divided into 

    (a.)    80 % of the training data -------------->  800 records for training

    (b.)    20 % of the testing  data -------------->  200 records for testing

#### Step 9: Train Random Forest Classifier Model

In [189]:
from sklearn.ensemble import RandomForestClassifier

#### create an object for Random Forest Classifier
rfc = RandomForestClassifier(n_estimators = 200,random_state=42)

#### using the object of Random Forest Classifier, train the model
rfc.fit(X_train, Y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

#### OBSERVATIONS:

1.  The object for Random Forest Classifier has been created with the following parameters :----

    (a.)    n_estimators = 200 ---------->   200 decision trees are used for the estimation of the model

    (b.)    random_state = 42 ----------->   ensures the reproducibility

2.  The model is trained with the help of the training data

#### Step 10: Perform the predictions of the model

In [190]:
#### predict the model
Y_pred = rfc.predict(X_test)

In [191]:
Y_pred

array([1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1])

#### OBSERVATIONS:

1.  The output has been predicted for the test data.

#### Step 11: Evaluate the Model

In [192]:
from sklearn.metrics import accuracy_score

ac = accuracy_score(Y_test, Y_pred)*100.0
print("Accuracy score of the model is:", ac)

Accuracy score of the model is: 78.0

#### OBSERVATIONS:

1.  The accuracy score of the Random Forest Classifier model using imdb movie review dataset is 78 % which is very high.

2.  So the model is working fine.

#### Step 12: Test with Custom Sentence

In [193]:
#### define the custom sentence

new_text = ["I really love this amazing course"]

#### perform the vectorization of the text
transformeddata = tfidf.transform(new_text)
print(transformeddata)

#### perform the prediction on the transformed data
predictions = rfc.predict(transformeddata)

print(predictions)

if(predictions[0]==1):
    print("Positive")
else:
    print("Negative")

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5 stored elements and shape (1, 17612)>
  Coords	Values
  (0, 725)	0.6122227075703419
  (0, 3685)	0.562669805305538
  (0, 9379)	0.4205627002884262
  (0, 12597)	0.32497192574535977
  (0, 15780)	0.16157446932027103
[1]
Positive

#### OBSERVATIONS:

1.  Positive sentiment is predicted for the input test data using Random Forest Classifier model.