#### To implement the Multiple Linear Regression based on the House Price dataset


##### Step 1: Import all the necessary libraries

In [1]:
import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns

from    sklearn.model_selection  import  train_test_split, StratifiedKFold, GridSearchCV
from    sklearn.preprocessing    import  StandardScaler
from    sklearn.linear_model     import  LinearRegression, Ridge, Lasso, ElasticNet
from    sklearn.metrics          import  mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

#### Step 2: Load the Dataset

In [2]:
df = pd.read_csv("Housing.csv")

In [3]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

#### OBSERVATIONS:

1.  The above dataset explains about the house pricing details for each and every house records.

2.  The independent features used in the dataset ranges from area ......... furnishingstatus

3.  The dependent   feature is the price of the house.

#### Step 3: Perform the Data Exploration

In [4]:
#### get the top five records in the dataset

df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [5]:
#### get the bottom five records in the dataset

df.tail()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [6]:
#### get the total length of the dataset

print("Length of the dataset is:", len(df))

Length of the dataset is: 545

In [7]:
#### get the shape of the dataset

print("Shape of the dataset is:", df.shape)

Shape of the dataset is: (545, 13)

In [8]:
#### get the columns used in the dataset

df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [9]:
#### get the information about each column in the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [10]:
#### get the descriptive statistics about the columns used in the dataset

df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

#### OBSERVATIONS:

1.  It explains about the descriptive statistical information about each numerical column used in the dataset.

#### Step 4: Perform Feature Engineering

In [11]:
cols = ['mainroad',	'guestroom',	'basement',	'hotwaterheating' ,'airconditioning', 'prefarea']


#### convert the categorical features into the numerical column by mapping them

for x in cols:
    df[x] = df[x].map({"yes":1, "no":0})

In [12]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,furnished
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,furnished
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,semi-furnished
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,furnished
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,furnished

In [13]:
#### perform the label encoding on the furnishingstatus column

from  sklearn.preprocessing  import  LabelEncoder

#### create an object for Label Encoder

label = LabelEncoder()

#### using the object of label encoder, transform the input

df['furnishingstatus'] = label.fit_transform(df['furnishingstatus'])

In [14]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0

In [15]:
#### Check for any NULL record in the dataset

df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

#### OBSERVATIONS:

1.  There are no NULL records in the dataset.

In [16]:
#### To check for the duplicate records in the dataset

df[df.duplicated()]

Empty DataFrame
Columns: [price, area, bedrooms, bathrooms, stories, mainroad, guestroom, basement, hotwaterheating, airconditioning, parking, prefarea, furnishingstatus]
Index: []

#### OBSERVATIONS:

1.  There are no duplicate records in the dataset.

#### Step 5: Divide the dataset into independent and dependent features

In [17]:
#### independent features

X = df.drop(columns='price',axis=1)

print(X)

     area  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
0    7420         4          2        3         1          0         0
1    8960         4          4        4         1          0         0
2    9960         3          2        2         1          0         1
3    7500         4          2        2         1          0         1
4    7420         4          1        2         1          1         1
..    ...       ...        ...      ...       ...        ...       ...
540  3000         2          1        1         1          0         1
541  2400         3          1        1         0          0         0
542  3620         2          1        1         1          0         0
543  2910         3          1        1         0          0         0
544  3850         3          1        2         1          0         0

     hotwaterheating  airconditioning  parking  prefarea  furnishingstatus
0                  0                1        2         1                 0
1                  0                1        3         0                 0
2                  0                0        2         1                 1
3                  0                1        3         1                 0
4                  0                1        2         0                 0
..               ...              ...      ...       ...               ...
540                0                0        2         0                 2
541                0                0        0         0                 1
542                0                0        0         0                 2
543                0                0        0         0                 0
544                0                0        0         0                 2

[545 rows x 12 columns]

In [18]:
#### dependent features

Y = df[['price']]

print(Y)

        price
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
..        ...
540   1820000
541   1767150
542   1750000
543   1750000
544   1750000

[545 rows x 1 columns]

#### Step 6: Divide the independent and dependent features into training and testing data

In [19]:
from  sklearn.model_selection  import  train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [20]:
X_train

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
46,6000,3,2,4,1,0,0,0,1,1,0,0
93,7200,3,2,1,1,0,1,0,1,3,0,1
335,3816,2,1,1,1,0,1,0,1,2,0,0
412,2610,3,1,2,1,0,1,0,0,0,1,2
471,3750,3,1,2,1,0,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
71,6000,4,2,4,1,0,0,0,1,0,0,2
106,5450,4,2,1,1,0,1,0,1,0,1,1
270,4500,3,2,3,1,0,0,1,0,1,0,0
435,4040,2,1,1,1,0,0,0,0,0,0,2
102,5500,3,2,4,1,1,0,0,1,1,0,1

In [21]:
X_test

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
316,5900,4,2,2,0,0,1,0,0,1,0,2
77,6500,3,2,3,1,0,0,0,1,0,1,0
360,4040,2,1,1,1,0,0,0,0,0,0,1
90,5000,3,1,2,1,0,0,0,1,0,0,1
493,3960,3,1,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
15,6000,4,1,2,1,0,1,0,0,2,0,1
357,6930,4,1,2,0,0,0,0,0,1,0,0
39,6000,4,2,4,1,0,0,0,1,1,0,1
54,6000,3,2,2,1,1,0,0,1,1,0,1
155,6100,3,2,1,1,0,1,0,0,2,1,0

In [22]:
print("Shape of the input training data is:", X_train.shape)

print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (436, 12)
Shape of the input testing  data is: (109, 12)

In [23]:
Y_train

       price
46   7525000
93   6300000
335  3920000
412  3430000
471  3010000
..       ...
71   6755000
106  6160000
270  4340000
435  3290000
102  6195000

[436 rows x 1 columns]

In [24]:
Y_test

       price
316  4060000
77   6650000
360  3710000
90   6440000
493  2800000
..       ...
15   9100000
357  3773000
39   7910000
54   7350000
155  5530000

[109 rows x 1 columns]

In [25]:
print("Shape of the output training data is:", Y_train.shape)

print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (436, 1)
Shape of the output testing  data is: (109, 1)

#### Step 7: Perform Feature Scaling on the inputs

In [26]:
from  sklearn.preprocessing  import  StandardScaler

#### create an object for Standard Scaler

sc = StandardScaler()

### using the object for Standard Scaler, transform the inputs

X_train_scaled = sc.fit_transform(X_train)

X_test_scaled = sc.transform(X_test)

In [27]:
X_train_scaled

array([[ 0.38416819,  0.05527092,  1.53917323, ...,  0.36795665,
        -0.55262032, -1.40940148],
       [ 0.9291807 ,  0.05527092,  1.53917323, ...,  2.70998729,
        -0.55262032, -0.07931697],
       [-0.60775457, -1.28351359, -0.5579503 , ...,  1.53897197,
        -0.55262032, -1.40940148],
       ...,
       [-0.29709744,  0.05527092,  1.53917323, ...,  0.36795665,
        -0.55262032, -1.40940148],
       [-0.5060189 , -1.28351359, -0.5579503 , ..., -0.80305867,
        -0.55262032,  1.25076755],
       [ 0.15707965,  0.05527092,  1.53917323, ...,  0.36795665,
        -0.55262032, -0.07931697]])

In [28]:
X_test_scaled

array([[ 0.33875048,  1.39405543,  1.53917323, ...,  0.36795665,
        -0.55262032,  1.25076755],
       [ 0.61125674,  0.05527092,  1.53917323, ..., -0.80305867,
         1.80956067, -1.40940148],
       [-0.5060189 , -1.28351359, -0.5579503 , ..., -0.80305867,
        -0.55262032, -0.07931697],
       ...,
       [ 0.38416819,  1.39405543,  1.53917323, ...,  0.36795665,
        -0.55262032, -0.07931697],
       [ 0.38416819,  0.05527092,  1.53917323, ...,  0.36795665,
        -0.55262032, -0.07931697],
       [ 0.4295859 ,  0.05527092,  1.53917323, ...,  1.53897197,
         1.80956067, -1.40940148]])

#### OBSERVATIONS:

1.  The input features have been scaled in the same input ranges.

#### Step 8: Train the Linear Model

In [29]:
from  sklearn.linear_model  import  LinearRegression

#### create an object for linear regression

ridge = Ridge(alpha=0.1)

#### using the object for linear regression, train the model

ridge.fit(X_train_scaled, Y_train)

Ridge(alpha=0.1)

#### Step 9: Predict the Model

In [30]:
Y_pred_ridge = ridge.predict(X_test_scaled)

In [31]:
Y_pred_ridge

array([[5203507.063658  ],
       [7256577.26230002],
       [3062983.89654945],
       [4559641.12517682],
       [3333209.89654651],
       [3563219.48698322],
       [5645471.05270151],
       [6413892.97106666],
       [2756057.07369427],
       [2669202.69857508],
       [9569913.51862456],
       [2827588.72523915],
       [3195696.61704477],
       [3352296.52770861],
       [3713941.13142618],
       [5300884.92707306],
       [2988081.52678613],
       [4810812.67601231],
       [4383017.66117169],
       [3525153.43517407],
       [5796014.95855357],
       [5839925.78836607],
       [2760385.50151057],
       [4762662.94253438],
       [5204750.70948231],
       [7515033.66943727],
       [3254856.68244129],
       [5236163.9917417 ],
       [8177988.17223865],
       [3434282.59989767],
       [6443586.35157254],
       [3346238.94652221],
       [6742122.47553041],
       [4154991.92431818],
       [3589407.96649519],
       [5787999.66248591],
       [4768526.106225  ],
       [4391815.75461928],
       [3217794.20334085],
       [4638344.37948038],
       [4522270.87204183],
       [3541372.75524926],
       [7237713.19949901],
       [4021704.37053373],
       [3702004.02393349],
       [4298874.57937448],
       [6704612.17090618],
       [3993746.20253937],
       [3798144.75635084],
       [3451935.47144641],
       [7293560.14854454],
       [2833121.84595932],
       [4378692.16666717],
       [4467885.09538012],
       [3714816.64707112],
       [2718720.86342771],
       [7524069.6311144 ],
       [2950691.32739127],
       [4194774.5694902 ],
       [2795991.42004746],
       [4801687.69823985],
       [3618213.70789953],
       [5091686.41099923],
       [4248030.37088115],
       [4729999.40132313],
       [4621033.57809851],
       [7215173.90067575],
       [3485214.369964  ],
       [5933761.43725601],
       [6236592.30116972],
       [4809649.48319958],
       [5130789.59825315],
       [4527246.66122508],
       [8006331.56451275],
       [3544076.26654928],
       [5462989.43485228],
       [3902668.6888995 ],
       [4660992.61603899],
       [4825482.02054796],
       [4276747.27451458],
       [7753797.03494115],
       [4008779.04215515],
       [6500872.47290548],
       [5386530.12507326],
       [2785630.77788248],
       [6836012.59049503],
       [2638880.409734  ],
       [3634453.49367533],
       [8003745.86705447],
       [8048016.52576288],
       [3227894.13901679],
       [5935157.44957645],
       [3605863.29151614],
       [3817819.66815124],
       [7631478.00699322],
       [4775431.41564611],
       [5093610.19272453],
       [6447051.7258047 ],
       [4943371.68896528],
       [5943759.46698806],
       [3810706.3827446 ],
       [6457412.25269434],
       [3701629.2946097 ],
       [5960170.48835115],
       [4933248.89564354],
       [4377232.07946149],
       [7009072.99952717],
       [6351362.00969104],
       [6409111.69572547]])

#### Step 10: Calculate the Slope and Intercept of the model

In [32]:
print("Slope of the model is:", ridge.coef_[0])


print("Intercept of the model is:", ridge.intercept_[0])

Slope of the model is: [ 519182.47357417   58777.02818203  523053.49900007  348098.31727342
  128141.7787476    89393.85833014  188405.86504245  150532.70239996
  362407.83994082  192799.40242038  266616.16757775 -158185.65334618]
Intercept of the model is: 4706527.385321101

#### Step 11: Evaluate the Regression Metrics

In [33]:
from    sklearn.metrics          import  mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

mae = mean_absolute_error(Y_test, Y_pred_ridge)
print("Mean Absolute Error of the model is:", mae)

Mean Absolute Error of the model is: 979666.5287590962

In [34]:
mse = mean_squared_error(Y_test, Y_pred_ridge)
print("Mean Squared Error of the model is:", mse)

Mean Squared Error of the model is: 1771808783138.1958

In [35]:
rmse = root_mean_squared_error(Y_test, Y_pred_ridge)
print("Root Mean Squared Error of the model is:", rmse)

Root Mean Squared Error of the model is: 1331093.078315035

In [36]:
r2ridge = r2_score(Y_test, Y_pred_ridge)
print("R2 Score of the model is:", r2ridge)

R2 Score of the model is: 0.6494640104340739

##### Step 12: Perform Hyper Parameter Tuning using GridSearchCV

In [37]:
#### define the pipeline

from  sklearn.pipeline  import Pipeline

#### create an object for pipeline

pipeline = Pipeline([
    ("sc"      ,       StandardScaler())             ,
    ("ridge"   ,       Ridge(alpha=0.1))
])

In [38]:
#### define the parameter grid

param_grid = {
    "ridge__alpha"  :  [0.01, 0.1, 1, 10, 100]
}

In [39]:
#### perform the cross validation

from  sklearn.model_selection import KFold

cv = KFold(n_splits=5, shuffle=True, random_state=42)

In [40]:
#### Create the object of GridSearchCV

grid = GridSearchCV(
    pipeline                            ,
    param_grid     =   param_grid       ,
    cv             =     cv             ,
    scoring        =     'r2'          
)

In [41]:
#### Train the model using the object of GridSearch CV

grid.fit(X_train_scaled, Y_train)

GridSearchCV(cv=KFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('sc', StandardScaler()),
                                       ('ridge', Ridge(alpha=0.1))]),
             param_grid={'ridge__alpha': [0.01, 0.1, 1, 10, 100]},
             scoring='r2')

#### OBSERVATIONS:

1. The GridSearchCV Model has been trained with the help of the training data.

In [42]:
#### get the best parameters and the estimators for the model

best_parameters = grid.best_params_

print("Best Parameters of the model is:", best_parameters)

Best Parameters of the model is: {'ridge__alpha': 10}

In [43]:
best_estimators = grid.best_estimator_

print("Best Estimators of the model is:", best_estimators)

Best Estimators of the model is: Pipeline(steps=[('sc', StandardScaler()), ('ridge', Ridge(alpha=10))])

In [44]:
#### using the best estimator, predict the model


Y_pred_grid = best_estimators.predict(X_test_scaled)

In [45]:
Y_pred_grid

array([[5186078.49228468],
       [7215424.63436571],
       [3078154.87651011],
       [4564276.36267827],
       [3359757.85705382],
       [3576607.92146009],
       [5645455.60222503],
       [6405077.05048196],
       [2777902.87179176],
       [2694752.0227472 ],
       [9503465.29446023],
       [2843010.90212358],
       [3197099.8043578 ],
       [3356094.61027054],
       [3720294.56045208],
       [5281326.70136989],
       [3003946.25786594],
       [4811920.14880486],
       [4382034.14539347],
       [3531314.53526903],
       [5772707.35418599],
       [5832334.89482507],
       [2777117.78847751],
       [4769574.85659592],
       [5204265.00850656],
       [7466253.50180209],
       [3271884.98967863],
       [5235969.77342821],
       [8126535.84227654],
       [3445786.52558435],
       [6411381.18461757],
       [3368797.4458539 ],
       [6722234.26601742],
       [4160415.22407493],
       [3613826.60698904],
       [5775581.1678268 ],
       [4783337.3932284 ],
       [4404361.85572548],
       [3231073.79950835],
       [4652176.08857165],
       [4532713.68270606],
       [3549980.36349883],
       [7196928.3217633 ],
       [4039770.38636305],
       [3704717.46591658],
       [4298421.41376399],
       [6667085.10501831],
       [4020326.6784457 ],
       [3794646.18551731],
       [3463268.96204276],
       [7251626.98600655],
       [2854142.69127538],
       [4378258.05057046],
       [4457035.53007701],
       [3733460.20392492],
       [2743304.84332852],
       [7487232.7283714 ],
       [2975254.39364738],
       [4211729.51229024],
       [2812029.57851455],
       [4792232.1549622 ],
       [3617006.57670886],
       [5091528.42020127],
       [4239531.59249632],
       [4733319.00561727],
       [4625677.743725  ],
       [7151324.02759622],
       [3496026.77014792],
       [5928064.19357442],
       [6237019.33661184],
       [4783915.97068653],
       [5118454.14848309],
       [4523916.5123144 ],
       [7954471.82981903],
       [3558337.70576026],
       [5453300.28225373],
       [3924424.03766744],
       [4654141.92222147],
       [4835745.5164644 ],
       [4271413.47932422],
       [7726671.49783901],
       [4028465.79605597],
       [6490233.23521712],
       [5361541.03161157],
       [2813411.65837634],
       [6802846.98750105],
       [2670288.60394225],
       [3655731.09552716],
       [7971747.63982087],
       [8010467.87381188],
       [3258731.80668764],
       [5933723.71241144],
       [3614788.74631585],
       [3822973.23888674],
       [7611865.86479648],
       [4805770.72956321],
       [5104775.54076875],
       [6410207.96332396],
       [4936058.66660376],
       [5927271.47517195],
       [3834254.51373072],
       [6455253.92032793],
       [3715124.33384501],
       [5929444.56134665],
       [4943890.26345396],
       [4386731.07605915],
       [6983624.27676095],
       [6341226.7918968 ],
       [6386995.42620725]])

In [46]:
#### Evaluate the Regression Metrics using GridSearchCV

from    sklearn.metrics          import  mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

maegrid = mean_absolute_error(Y_test, Y_pred_grid)
print("Mean Absolute Error of the model is:", maegrid)

Mean Absolute Error of the model is: 978653.4031173647

In [47]:
msegrid = mean_squared_error(Y_test, Y_pred_grid)
print("Mean Squared Error of the model is:", msegrid)

Mean Squared Error of the model is: 1778081197208.6943

In [48]:
rmsegrid = root_mean_squared_error(Y_test, Y_pred_grid)
print("Root Mean Squared Error of the model is:", rmsegrid)

Root Mean Squared Error of the model is: 1333447.110765438

In [49]:
r2grid = r2_score(Y_test, Y_pred_grid)
print("R2 Score of the model is:", r2grid)

R2 Score of the model is: 0.648223071290926

#### OBSERVATIONS:

1.  The R2 Score of the model remains the same as 0.64 even after applying the Grid Search CV operation.