#### Perform the Standard Scaling on the dataset

In [61]:
#### import  all the important features

import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns


from   sklearn.preprocessing  import  StandardScaler, MinMaxScaler

In [62]:
#### Load the dataset

df = pd.read_csv("diabetes.csv")

In [63]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

#### OBSERVATIONS:

1.  The above dataset explains about the diabetic situation for each and every patient and tells whether the patient is suffering from diabetes or not.

In [64]:
#### Divide the dataset into independent and dependent features

X = df.drop(columns='Outcome', axis=1)

In [65]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [66]:
Y = df[['Outcome']]

In [67]:
Y

     Outcome
0          1
1          0
2          1
3          0
4          1
..       ...
763        0
764        0
765        0
766        1
767        0

[768 rows x 1 columns]

#### Perform the Standard Scaling on the inputs

##### (a.)  Standard Scaler

In [68]:
from  sklearn.preprocessing     import  StandardScaler

#### create an object for Standard Scaler

sc = StandardScaler()


#### using the object of standard scaler, transform the inputs

X_scaled = sc.fit_transform(X)

In [69]:
X_scaled

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

#### OBSERVATIONS:

1.  After applying Standard Scaler on the inputs , all these inputs has been transformed into the scale of one range from 0 to 1.

#### (b.)  Min Max Scaler

In [70]:
from  sklearn.preprocessing  import MinMaxScaler

#### create an object for min max scaler

minmax = MinMaxScaler()


#### using the object for min max scaler, transform the inputs

X_minmax = minmax.fit_transform(X)

In [71]:
X_minmax

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

#### OBSERVATIONS:

1.  After applying Min max Scaler on the inputs , all these inputs has been transformed into the scale of one range from -1 to 1.